/// AOT backend generation for `.slint` files: `*.aot.g.dart` libraries that
/// bind the code asset built by `buildSlintAot` (`aot_build.dart`), exposing
/// one `SlintCompilerFactory` per component.
///
/// This is the build-time half; the runtime half those libraries import lives
/// in `runtime.dart`, and the typed API is generated by
/// `package:slint_generator`.
library;

export 'src/generator.dart';
