/// AOT backend generation for `.slint` files: `*.aot.g.dart` libraries that
/// bind the code asset built by `buildSlintAot` (`aot_build.dart`), exposing
/// one `SlintComponentFactory` per component.
///
/// The typed API is generated by `package:slint_generator`.
library;

export 'src/generator.dart';
