name: slint_dart_workspace
publish_to: none

environment:
  sdk: ^3.13.0

workspace:
  - slint
  - slint_build
  - slint_compiler
  - slint_generator
  - slint_interpreter
  - slint_skia
  - example

