import 'dart:convert';

import 'package:dart_style/dart_style.dart';
import 'package:pub_semver/pub_semver.dart';

import 'names.dart';
import 'schema.dart';

/// Generates the typed wrapper library for one `.slint` file.
///
/// One class per exported component and one per named struct, so the whole
/// public interface is statically typed: `List<TodoItem>` rather than
/// `List<Object?>`, named callback parameters rather than positional
/// `List<Object?>` arguments. The JSON shape the backends speak is confined to
/// the generated `fromSlint`/`toSlint` conversions.
///
/// Backend-agnostic: instances come from a `SlintComponentFactory`, so the
/// same wrapper runs on the interpreter (`slint_interpreter`) or on
/// AOT-compiled code (`slint_compiler`). [slintSource] is embedded for the
/// backends that compile at runtime; [sourceName] only labels the header.
///
/// [aotLibrary] names the sibling `*.aot.g.dart` when the package depends on
/// `slint_compiler`, and [interpreter] says whether it depends on
/// `slint_interpreter`. Whichever backends are available become the default of
/// `create()`, so callers need no wiring; with both, the default follows the
/// build mode, exactly like the hooks deciding which dylib to bundle.
String generateWrapperLibrary(
  SlintSchema schema, {
  required String sourceName,
  required String slintSource,
  String? assetPath,
  String? aotLibrary,
  bool interpreter = false,
  Map<String, List<int>> slintFiles = const {},
}) {
  final structs = <String, TypeRef>{};
  final enums = <String, TypeRef>{};
  for (final component in schema.components) {
    for (final prop in component.properties) {
      _collectTypes(prop.type, structs, enums);
    }
    for (final cb in component.callbacks) {
      for (final arg in cb.args) {
        _collectTypes(arg.type, structs, enums);
      }
      if (cb.returnType != null) _collectTypes(cb.returnType!, structs, enums);
    }
  }
  for (final global in schema.globals) {
    for (final prop in global.properties) {
      _collectTypes(prop.type, structs, enums);
    }
  }

  // Structs holding lists need element-wise comparison; identity would make
  // two equal values compare unequal.
  final deepEquality = structs.values.any(
    (s) => s.fields!.any((f) => f.type.kind == 'array'),
  );

  final imports = StringBuffer(
    "import 'package:slint/slint_core.dart';\n"
    "import 'package:slint_generator/runtime.dart';\n",
  );
  if (interpreter) {
    imports.write(
      "import 'package:slint_interpreter/slint_interpreter.dart';\n",
    );
  }
  if (aotLibrary != null) {
    imports.write("\nimport '$aotLibrary' as aot;\n");
  }

  final b = StringBuffer('''
// GENERATED by slint_generator from $sourceName — do not edit.
// ignore_for_file: type=lint
library;

$imports
/// `$sourceName`, embedded so the interpreter can compile it at runtime.
///
/// Only the interpreter factory's construction names it, and in a build
/// that defaults to the AOT backend that is a const-dead branch, so the tree
/// shaker drops the string with it: the UI source is not in the shipped
/// binary.
const _source = ${dartStringLiteral(slintSource)};

/// What `$sourceName` reads besides itself — `import`ed `.slint` files and
/// `@image-url` resources — base64 by path relative to it, so the interpreter
/// is handed the same tree. Like the source above, named only where the
/// interpreter factory is built.
const _files = <String, String>{${_filesEntries(slintFiles)}};
''');

  if (interpreter && aotLibrary != null) {
    b.write('''

/// True in release and profile builds — the same condition the build hooks
/// use (`linkingEnabled`) to bundle the AOT dylib instead of the interpreter,
/// spelled without a Flutter import.
const _useCompiled = bool.fromEnvironment('dart.vm.product') ||
    bool.fromEnvironment('dart.vm.profile');
''');
  }

  if (deepEquality) b.write(_deepHelpers);

  for (final en in enums.values) {
    b.write(_enumDart(en, sourceName));
  }

  for (final struct in structs.values) {
    b.write(_structDart(struct, sourceName, deepEquality: deepEquality));
  }

  for (final component in schema.components) {
    b.write(
      _componentDart(
        component,
        sourceName,
        assetPath: assetPath,
        aotLibrary: aotLibrary,
        interpreter: interpreter,
      ),
    );
  }
  for (final global in schema.globals) {
    b.write(_globalDart(global, sourceName));
  }
  // Formatting is not cosmetic here: it parses, so a template that would emit
  // unparseable Dart fails the build instead of the app.
  return _formatter.format(b.toString());
}

final _formatter = DartFormatter(languageVersion: Version(3, 13, 0));

String _filesEntries(Map<String, List<int>> files) => [
  for (final path in files.keys.toList()..sort())
    '\n  ${dartStringLiteral(path)}: '
        '${dartStringLiteral(base64Encode(files[path]!))},',
].join();

/// Encodes [value] as a Dart string literal (JSON escaping plus `$`, which
/// Dart would otherwise read as interpolation).
String dartStringLiteral(String value) =>
    jsonEncode(value).replaceAll(r'$', r'\$');

const _deepHelpers = '''

bool _eq(Object? a, Object? b) {
  if (identical(a, b)) return true;
  if (a is List && b is List) {
    if (a.length != b.length) return false;
    for (var i = 0; i < a.length; i++) {
      if (!_eq(a[i], b[i])) return false;
    }
    return true;
  }
  return a == b;
}

int _hash(Object? v) =>
    v is List ? Object.hashAll([for (final e in v) _hash(e)]) : v.hashCode;
''';

void _collectTypes(
  TypeRef type,
  Map<String, TypeRef> structs,
  Map<String, TypeRef> enums,
) {
  switch (type.kind) {
    case 'struct':
      if (structs.containsKey(type.structName!)) return;
      structs[type.structName!] = type;
      for (final field in type.fields!) {
        _collectTypes(field.type, structs, enums);
      }
    case 'enum':
      if (enums.containsKey(type.enumName!)) return;
      enums[type.enumName!] = type;
    case 'array':
      _collectTypes(type.element!, structs, enums);
  }
}

/// Dart type for a schema type. Throws for anything the backends cannot
/// marshal, so generation fails loudly rather than emitting `Object?`.
String _dartType(TypeRef type) => switch (type.kind) {
  'float' || 'length' || 'angle' || 'percent' || 'duration' => 'double',
  'int' => 'int',
  'string' => 'String',
  'bool' => 'bool',
  'color' => 'SlintColor',
  'brush' => 'SlintBrush',
  'image' => 'String',
  'enum' => pascalCase(type.enumName!),
  'struct' => pascalCase(type.structName!),
  'array' => 'List<${_dartType(type.element!)}>',
  _ => throw StateError('unsupported property type: ${type.kind}'),
};

/// Whether reading [type] off the bridge needs more than a cast — true for
/// every numeric kind too, since the bridge hands back `num`.
bool _reads(TypeRef type) => switch (type.kind) {
  'string' || 'bool' || 'image' => false,
  'array' => _reads(type.element!),
  _ => true,
};

/// Whether writing [type] needs conversion. Only structs do; every other
/// typed value is already what the bridge expects.
bool _writes(TypeRef type) => switch (type.kind) {
  'struct' || 'color' || 'brush' || 'enum' => true,
  'array' => _writes(type.element!),
  _ => false,
};

/// Reads [expr] — an `Object?` off the bridge — as the typed value.
String _fromWire(String expr, TypeRef type) => switch (type.kind) {
  'float' ||
  'length' ||
  'angle' ||
  'percent' ||
  'duration' => '($expr as num).toDouble()',
  'int' => '($expr as num).toInt()',
  'string' || 'image' => '$expr as String',
  'bool' => '$expr as bool',
  'color' => 'SlintColor.fromSlint($expr as String)',
  'brush' => 'SlintBrush.fromSlint($expr as String)',
  'enum' => '${pascalCase(type.enumName!)}.fromSlint($expr as String)',
  'struct' =>
    '${pascalCase(type.structName!)}.fromSlint($expr as Map<Object?, Object?>)',
  'array' =>
    _reads(type.element!)
        ? '[for (final e in $expr as List<Object?>) ${_fromWire('e', type.element!)}]'
        : '($expr as List<Object?>).cast<${_dartType(type.element!)}>()',
  _ => throw StateError('unsupported property type: ${type.kind}'),
};

/// Writes the typed [expr] back into the shape the bridge expects.
String _toWire(String expr, TypeRef type) => switch (type.kind) {
  'struct' || 'color' || 'brush' || 'enum' => '$expr.toSlint()',
  'array' when _writes(type.element!) =>
    '[for (final e in $expr) ${_toWire('e', type.element!)}]',
  _ => expr,
};

/// Members of every generated enum; a variant must not take one.
const _enumMembers = {'fromSlint', 'toSlint', ...objectMembers};

String _enumDart(TypeRef en, String sourceName) {
  final name = pascalCase(en.enumName!);
  final variants = en.variants!;
  final taken = <String>{..._enumMembers};
  final dart = <String, String>{};
  for (final v in variants) {
    dart[v] = dartName(v, taken);
    taken.add(dart[v]!);
  }
  final values = variants.map((v) => "  ${dart[v]!}('$v'),").join('\n');
  final fromArms = variants.map((v) => "      '$v' => ${dart[v]!},").join('\n');
  return '''

/// `${en.enumName}`, an enum declared in `$sourceName`.
enum $name {
$values;

  const $name(this._wire);
  final String _wire;

  factory $name.fromSlint(String wire) {
    const prefix = '$name.';
    final variant =
        wire.startsWith(prefix) ? wire.substring(prefix.length) : wire;
    return switch (variant) {
$fromArms
      _ => throw ArgumentError.value(wire, 'wire', 'unknown $name variant'),
    };
  }

  String toSlint() => '$name.\$_wire';
}
''';
}

String _structDart(
  TypeRef struct,
  String sourceName, {
  required bool deepEquality,
}) {
  final name = pascalCase(struct.structName!);
  final fields = struct.fields!;
  final dart = {
    for (final f in fields) f.name: dartName(f.name, _structMembers),
  };
  final types = {for (final f in fields) f.name: _dartType(f.type)};

  final ctorParams = fields
      .map((f) => 'required this.${dart[f.name]}')
      .join(', ');
  final declarations = fields
      .map((f) => '  final ${types[f.name]} ${dart[f.name]};')
      .join('\n');
  final fromSlint = fields
      .map(
        (f) =>
            "        ${dart[f.name]}: ${_fromWire("value['${f.name}']", f.type)},",
      )
      .join('\n');
  final toSlint = fields
      .map((f) => "        '${f.name}': ${_toWire(dart[f.name]!, f.type)},")
      .join('\n');
  final copyParams = fields
      .map((f) => '${types[f.name]}? ${dart[f.name]}')
      .join(', ');
  final copyArgs = fields
      .map(
        (f) =>
            '        ${dart[f.name]}: ${dart[f.name]} ?? this.${dart[f.name]},',
      )
      .join('\n');

  final eq = fields
      .map(
        (f) => deepEquality
            ? '_eq(${dart[f.name]}, other.${dart[f.name]})'
            : '${dart[f.name]} == other.${dart[f.name]}',
      )
      .join(' &&\n          ');
  final hashArgs = fields
      .map((f) => deepEquality ? '_hash(${dart[f.name]})' : dart[f.name]!)
      .join(', ');
  final toStringFields = fields
      .map((f) => '${dart[f.name]}: \$${dart[f.name]}')
      .join(', ');

  return '''

/// `${struct.structName}`, a struct declared in `$sourceName`.
class $name {
  const $name({$ctorParams});

  /// Reads the value as the backends represent it.
  factory $name.fromSlint(Map<Object?, Object?> value) => $name(
$fromSlint
      );

$declarations

  /// The representation the backends expect, keyed by the Slint field names.
  Map<String, Object?> toSlint() => {
$toSlint
      };

  $name copyWith({$copyParams}) => $name(
$copyArgs
      );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is $name &&
          $eq;

  @override
  int get hashCode => Object.hash($hashArgs);

  @override
  String toString() => '$name($toStringFields)';
}
''';
}

/// Members of every generated struct class; a field must not take one.
const _structMembers = {'fromSlint', 'toSlint', 'copyWith', ...objectMembers};

/// Members of every generated component wrapper (static and instance share
/// one namespace in Dart); a property or callback must not take one.
const _componentMembers = {
  'component', 'componentName', 'slintSource', 'slintFiles', 'assetPath', //
  'defaultFactory', 'create', 'load', 'register', 'renderTarget', 'dispose',
  'getProperty', 'setProperty', 'setCallbackHandler', 'invokeCallback',
  ...objectMembers,
};

/// Names a callback parameter must not shadow: the wrapper's `component`
/// field the invoke body calls through, and the locals of the generated
/// adapters and list conversions.
const _paramTaken = {'component', 'handler', 'arguments', 'e'};

/// Dart parameter names for a callback's arguments — the declared names when
/// the compiler reported them, positional fallbacks otherwise.
List<String> _argNames(CallbackSchema cb) => [
  for (var i = 0; i < cb.args.length; i++)
    cb.args[i].name.isEmpty
        ? 'arg${i + 1}'
        : dartName(cb.args[i].name, _paramTaken),
];

/// The `on<X>`/`invoke<X>` method names for [cb], escaped like [dartName]
/// when they would collide with a wrapper member (`callback callback` would
/// otherwise emit a second `invokeCallback`).
({String on, String invoke}) _callbackMethods(CallbackSchema cb) {
  String escape(String n) => _componentMembers.contains(n) ? '${n}_' : n;
  final p = pascalCase(cb.name);
  return (on: escape('on$p'), invoke: escape('invoke$p'));
}

String _globalDart(GlobalSchema global, String sourceName) {
  final pascal = pascalCase(global.name);
  final members = StringBuffer();
  for (final prop in global.properties) {
    final name = dartName(prop.name, const {});
    final type = _dartType(prop.type);
    members.write('''

  $type get $name => throw UnsupportedError(
      'Global property accessors are not yet supported by the interpreter backend');
  set $name($type value) => throw UnsupportedError(
      'Global property accessors are not yet supported by the interpreter backend');
''');
  }

  return '''

/// Typed accessor for the `$pascal` global of `$sourceName`.
///
/// Global properties are not yet reachable through the interpreter FFI;
/// every member throws [UnsupportedError] until a backend exposes them.
class $pascal {
  $pascal(this.component);

  final SlintComponent component;
$members}
''';
}

String _componentDart(
  ComponentSchema component,
  String sourceName, {
  required String? assetPath,
  required String? aotLibrary,
  required bool interpreter,
}) {
  // A Slint component name may contain dashes; the class name may not. The
  // backends keep addressing the component by its Slint name.
  final pascal = pascalCase(component.name);
  final members = StringBuffer();
  final methods = {
    for (final cb in component.callbacks) cb.name: _callbackMethods(cb),
  };
  // Properties avoid the wrapper's members and the callbacks' methods alike
  // (`on-add-todo` would otherwise collide with `add-todo`'s handler setter).
  final taken = {
    ..._componentMembers,
    for (final m in methods.values) ...[m.on, m.invoke],
  };

  for (final prop in component.properties) {
    final name = dartName(prop.name, taken);
    if (prop.type.kind == 'array') {
      final element = prop.type.element!;
      final fromWire = _fromWire('e', element);
      final toWire = _toWire('e', element);
      members.write('''

  late final $name = SlintListModel<${_dartType(element)}>(
    () => component.getProperty('${prop.name}'),
    (value) => component.setProperty('${prop.name}', value),
    (e) => $fromWire,
    (e) => $toWire,
  );
''');
    } else {
      final type = _dartType(prop.type);
      final read = _fromWire(
        "component.getProperty('${prop.name}')",
        prop.type,
      );
      final write = _toWire('value', prop.type);
      members.write('''

  $type get $name => $read;
  set $name($type value) => component.setProperty('${prop.name}', $write);
''');
    }
  }

  for (final cb in component.callbacks) {
    final m = methods[cb.name]!;
    final names = _argNames(cb);
    final params = [
      for (var i = 0; i < cb.args.length; i++)
        '${_dartType(cb.args[i].type)} ${names[i]}',
    ].join(', ');
    final returns = cb.returnType == null ? 'void' : _dartType(cb.returnType!);

    final unpacked = [
      for (var i = 0; i < cb.args.length; i++)
        _fromWire('arguments[$i]', cb.args[i].type),
    ].join(', ');
    // A void handler still has to answer the bridge, which expects a value.
    final adapter = cb.returnType == null
        ? '(arguments) {\n        handler($unpacked);\n        return null;\n      }'
        : '(arguments) => ${_toWire('handler($unpacked)', cb.returnType!)}';

    final invokeArgs = [
      for (var i = 0; i < cb.args.length; i++)
        _toWire(names[i], cb.args[i].type),
    ].join(', ');
    final call = "component.invokeCallback('${cb.name}', [$invokeArgs])";

    members.write('''

  /// Handles the `${cb.name}` callback; replaces any previous handler.
  void ${m.on}($returns Function($params) handler) =>
      component.setCallbackHandler('${cb.name}', $adapter);

  /// Invokes the `${cb.name}` callback.
  $returns ${m.invoke}($params) =>
      ${cb.returnType == null ? call : _fromWire(call, cb.returnType!)};
''');
  }

  final aotFactory = aotLibrary == null
      ? null
      : 'aot.${aotFactoryName(component.name)}';
  final (defaultFactory, defaultDoc) = switch ((aotFactory, interpreter)) {
    (final String f, true) => (
      '_useCompiled ? $f : SlintInterpreterFactory(_source, files: _files)',
      'the AOT-compiled component in release and profile builds, the\n'
          '  /// interpreter in debug, matching the dylib the build bundles',
    ),
    (final String f, false) => (f, 'the AOT-compiled component'),
    (null, true) => (
      'SlintInterpreterFactory(_source, files: _files)',
      'the interpreter',
    ),
    (null, false) => (null, ''),
  };

  final create = defaultFactory == null
      ? '''
  /// Instantiates `$pascal` through [factory].
  static $pascal create(SlintComponentFactory factory) =>
      $pascal(factory.instantiate(componentName));
'''
      : '''
  /// Backend [create] uses when given none —
  /// $defaultDoc.
  ///
  /// Created once, on first use, and shared by every instance.
  static final SlintComponentFactory defaultFactory = $defaultFactory;

  /// Instantiates `$pascal` through [factory], or [defaultFactory].
  static $pascal create([SlintComponentFactory? factory]) =>
      $pascal((factory ?? defaultFactory).instantiate(componentName));
''';

  // The mode split lives in `defaultFactory`, whose `_useCompiled` is a
  // const: a release build initializes it to the AOT factory and the
  // interpreter branch — the only mention of `_source` — is dead code the
  // tree shaker drops, string and all. Emitting two literal bodies here
  // instead would need a factory per branch, and constructing
  // `SlintInterpreterFactory(_source)` per call leaks an engine.
  final loadModeDoc = (interpreter && aotFactory != null)
      ? '''
  /// Debug builds compile the source captured at generation time with the
  /// interpreter; release and profile builds use the component slint-build
  /// compiled into the app. Neither reads the file.'''
      : (interpreter
            ? '''
  /// Compiles the source captured at generation time with the interpreter;
  /// the file itself is never read.'''
            : '''
  /// Uses the component slint-build compiled into the app; the file itself
  /// is never read.''');

  final load = (defaultFactory == null || assetPath == null)
      ? ''
      : '''

  /// Path of the `.slint` file this wrapper was generated from — the name
  /// [load] answers to.
  ///
  /// The source at that path is embedded below and, in release, compiled
  /// into the app's own binary, so the file itself never has to ship.
  static const assetPath = '$assetPath';

  /// Instantiates `$pascal` from the `.slint` file at [path].
$loadModeDoc
  ///
  /// [path] names the UI the same way in every build mode; what backs it is
  /// whatever that mode compiled. It must be a single `.slint` file, and it
  /// must be [assetPath] — this wrapper was generated from that file; every
  /// other `.slint` gets a wrapper of its own.
  ///
  /// Synchronous: the instance is usable — and renderable — on return.
  static $pascal load(String path) {
    if (!path.endsWith('.slint')) {
      throw ArgumentError.value(path, 'path', 'not a .slint file');
    }
    if (path != assetPath) {
      throw ArgumentError.value(
          path, 'path', '$pascal was generated from \$assetPath');
    }
    return $pascal(defaultFactory.instantiate(componentName));
  }

  /// Makes `SlintComponent.load(assetPath)` return a `$pascal`.
  ///
  /// Call once at startup. Registration is per component, not per file, so
  /// a component the app never registers is still tree-shaken out of a
  /// release build.
  static void register() =>
      SlintComponent.register<$pascal>(assetPath, componentName, create);
''';

  final example = switch ((defaultFactory, assetPath)) {
    (null, _) =>
      'final app = $pascal(component); // a SlintComponent from any backend',
    (_, null) => 'final app = $pascal.create();',
    (_, final path) =>
      "$pascal.register(); // once, at startup\n/// final app = SlintComponent.load<$pascal>('$path');",
  };

  return '''

/// Typed wrapper for the `$pascal` component of `$sourceName`.
///
/// ```dart
/// $example
/// ```
class $pascal implements SlintSoftwareComponent {
  $pascal(this.component);

  /// Name of the exported component this wrapper drives.
  static const componentName = '${component.name}';

  /// The `.slint` source this wrapper was generated from.
  static const slintSource = _source;

  /// What [slintSource] reads besides itself, base64 by path relative to it.
  static const slintFiles = _files;

$create$load
  /// The backing instance, from any backend. App code goes through the typed
  /// members; the untyped bridge below is what the backends implement.
  final SlintComponent component;

  /// The target to hand a `SlintView`. Only a backend that renders in
  /// software has one; a texture backend (slint_skia) does not.
  @override
  SlintSoftwareRenderTarget get renderTarget => switch (component) {
        final SlintSoftwareComponent c => c.renderTarget,
        _ => throw StateError(
            '\${component.runtimeType} does not render through a software target'),
      };

  @override
  void dispose() => component.dispose();

  @override
  Object? getProperty(String name) => component.getProperty(name);

  @override
  void setProperty(String name, Object? value) =>
      component.setProperty(name, value);

  @override
  void setCallbackHandler(String name, SlintCallbackHandler handler) =>
      component.setCallbackHandler(name, handler);

  @override
  Object? invokeCallback(String name, List<Object?> arguments) =>
      component.invokeCallback(name, arguments);
$members}
''';
}
