import 'package:slint/slint_core.dart';

/// Creates instances of a component for one backend.
///
/// The typed wrappers generated by this package take a factory, so the same
/// generated API runs on either backend — `SlintInterpreterFactory`
/// (`slint_interpreter`) carries `.slint` source and compiles it at runtime,
/// `SlintCompilerFactory` (`slint_compiler`) binds one AOT-compiled
/// component:
///
/// ```dart
/// final app = TodoApp.create(SlintInterpreterFactory(TodoApp.slintSource));
/// ```
///
/// The source lives in the factory rather than being passed to [instantiate]
/// on purpose: a generated wrapper then mentions its embedded source only
/// where it constructs the interpreter factory, which a release build
/// tree-shakes away together with the source string.
///
/// `base` on purpose: a backend must `extend` this, so every factory is a real
/// subtype rather than a structural look-alike.
abstract base class SlintComponentFactory {
  const SlintComponentFactory();

  /// Instantiates the component named [componentName]. Synchronous on every
  /// backend: compiling with the interpreter and creating an AOT instance are
  /// each a single FFI call.
  SlintSoftwareComponent instantiate(String componentName);
}
