import 'dart:io';

import 'cargo_builder.dart' show packageInConfig, packageRootFromConfig;

/// The Rust crates the slint_dart packages carry, by package: the members of
/// the workspace [stageCargoWorkspace] builds them in.
const cargoCrates = <String, List<String>>{
  'slint': ['rust'],
  'slint_build': ['interpreter'],
  'slint_generator': ['rust'],
  'slint_interpreter': ['rust'],
  'slint_skia': ['rust'],
  'slint_testing': ['rust'],
};

/// The staged workspace manifest after its member list. It equals the repo's
/// root `Cargo.toml` from `[workspace.dependencies]` on, and a test holds the
/// two together: bump the Slint pin in both, and in `slint_compiler`'s
/// `slintVersion`.
const cargoWorkspaceShared = '''
[workspace.dependencies]
slint = { version = "=1.18.0", default-features = false }
slint-interpreter = { version = "=1.18.0", default-features = false }
i-slint-compiler = "=1.18.0"
i-slint-backend-testing = { version = "=1.18.0", default-features = false }
# No default features: the default pulls in `softbuffer`, whose 0.4.8 (the
# newest release) cannot compile for Linux targets — with no backend feature
# enabled (Slint enables none) its dispatch enums are empty, rejected by
# current rustc (E0392/E0004). Nothing here uses it: every surface is custom
# (metal/d3d/gl/android), so the softbuffer fallback is dead weight.
i-slint-renderer-skia = { version = "=1.18.0", default-features = false }
i-slint-core = "=1.18.0"
serde_json = "1"
spin_on = "0.1"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
dbg_macro = "warn"
todo = "warn"
''';

/// Stages the Cargo workspace every crate builds in, next to [packageConfig]
/// (`.dart_tool/slint_cargo/`), and returns its root.
///
/// The crates inherit dependencies and lints from a workspace
/// (`workspace = true`) and reach each other by relative path
/// (`../../slint/rust`). In this repo the root `Cargo.toml` is that
/// workspace; a package from pub.dev sits in the pub cache as `slint-0.0.1/`,
/// with no workspace above it and no sibling called `slint`. So builds go
/// through a workspace of their own: a link `packages/<name>` to each
/// package root the config lists, under a generated manifest. Cargo walks
/// paths lexically, so `../../slint/rust` lands on a link, the links find
/// this manifest as their workspace root, and `target/` and `Cargo.lock`
/// stay here rather than in the pub cache.
///
/// Safe to call on every build, from concurrent hooks: files are rewritten
/// only when their content changes, and atomically.
String? _cachedWorkspaceConfigKey;
Uri? _cachedWorkspaceRoot;

Uri stageCargoWorkspace(Uri packageConfig) {
  final configKey = packageConfig.toFilePath();
  final cached = _cachedWorkspaceRoot;
  if (_cachedWorkspaceConfigKey == configKey && cached != null) {
    return cached;
  }
  final root = packageConfig.resolve('slint_cargo/');
  final members = <String>[];
  for (final MapEntry(key: name, value: crates) in cargoCrates.entries) {
    if (!packageInConfig(packageConfig, name)) continue;
    _link(
      Link.fromUri(root.resolve('packages/$name')),
      Directory.fromUri(packageRootFromConfig(packageConfig, name)).path,
    );
    members.addAll([for (final c in crates) 'packages/$name/$c']);
  }
  _writeIfChanged(File.fromUri(root.resolve('Cargo.toml')), '''
# GENERATED by slint_build (stageCargoWorkspace) — do not edit. Rewritten on
# every build from the package config: one member per slint_dart crate the
# app depends on, each reached through a link under packages/.
[workspace]
resolver = "2"
members = [
${members.map((m) => '    "$m",\n').join()}]

$cargoWorkspaceShared''');

  // The repo's lock pins the tree; the staged one starts from it, and again
  // whenever it changes. A pub consumer has none and resolves afresh.
  // ponytail: pub consumers get unpinned transitive crates; ship a copy of
  // the lock in slint_build if a transitive release ever breaks them.
  final seed = cargoLockSeed(packageConfig);
  if (seed != null) {
    final lock = seed.readAsStringSync();
    final marker = File.fromUri(root.resolve('Cargo.lock.seed'));
    if (!marker.existsSync() || marker.readAsStringSync() != lock) {
      _writeIfChanged(File.fromUri(root.resolve('Cargo.lock')), lock);
      _writeIfChanged(marker, lock);
    }
  }
  _cachedWorkspaceConfigKey = configKey;
  _cachedWorkspaceRoot = root;
  return root;
}

/// [packageName]'s crate manifest in the staged workspace
/// ([stageCargoWorkspace]).
Uri stagedCargoManifest(
  Uri packageConfig,
  String packageName, {
  String crate = 'rust',
}) =>
    stageCargoWorkspace(packageConfig)
        .resolve('packages/$packageName/$crate/Cargo.toml');

/// The repo's `Cargo.lock` when the packages come from a checkout of it (this
/// repo, or a git dependency); null in the pub cache.
File? cargoLockSeed(Uri packageConfig) {
  final lock = File.fromUri(
    packageRootFromConfig(
      packageConfig,
      'slint_build',
    ).resolve('../../Cargo.lock'),
  );
  return lock.existsSync() ? lock : null;
}

void _link(Link link, String target) {
  if (target.length > 1 && target.endsWith(Platform.pathSeparator)) {
    target = target.substring(0, target.length - 1);
  }
  try {
    if (link.existsSync()) {
      if (link.targetSync() == target) return;
      link.deleteSync();
    }
    link.createSync(target, recursive: true);
  } on FileSystemException {
    // A concurrent hook staged the same link first.
    if (!link.existsSync() || link.targetSync() != target) rethrow;
  }
}

void _writeIfChanged(File file, String content) {
  if (file.existsSync() && file.readAsStringSync() == content) return;
  file.parent.createSync(recursive: true);
  final tmp = File('${file.path}.$pid.tmp')..writeAsStringSync(content);
  tmp.renameSync(file.path);
}
