// GENERATED by slint_generator from todo.slint — do not edit.
// ignore_for_file: type=lint
library;

import 'package:slint/slint_core.dart';
import 'package:slint_generator/runtime.dart';

/// `todo.slint`, embedded so the interpreter can compile it at runtime.
///
/// Only the interpreter factory's construction names it, and in a build
/// that defaults to the AOT backend that is a const-dead branch, so the tree
/// shaker drops the string with it: the UI source is not in the shipped
/// binary.
const _source =
    "import { TodoItem, TodoView } from \"../../todo_shared/ui/todo_view.slint\";\n\n// Re-exported: the generated Dart and the AOT glue name the row type.\nexport { TodoItem }\n\nexport component TodoApp inherits Window {\n    preferred-width: 400px;\n    preferred-height: 600px;\n    title: \"Slint ♥ Flutter — Todo (Skia)\";\n\n    // Host (Dart) owns the list; this default renders before the host syncs.\n    in property <[TodoItem]> todo-model: [\n        { title: \"Wire Slint into Flutter\", checked: true },\n        { title: \"Render this list\", checked: false },\n    ];\n\n    // Named arguments carry through to the generated Dart signatures.\n    callback add-todo(title: string);\n    callback toggle-todo(index: int, checked: bool);\n    callback remove-done();\n\n    // The list itself is shared with the other example:\n    // examples/todo_shared/ui/todo_view.slint.\n    TodoView {\n        todo-model: root.todo-model;\n        add-todo(title) => { root.add-todo(title); }\n        toggle-todo(index, checked) => { root.toggle-todo(index, checked); }\n        remove-done => { root.remove-done(); }\n    }\n}\n";

/// What `todo.slint` reads besides itself — `import`ed `.slint` files and
/// `@image-url` resources — base64 by path relative to it, so the interpreter
/// is handed the same tree. Like the source above, named only where the
/// interpreter factory is built.
const _files = <String, String>{
  "../../todo_shared/ui/todo_view.slint": "Ly8gVGhlIHRvZG8gbGlzdCBVSSBib3RoIGV4YW1wbGVzIHNob3c6IGV4YW1wbGVzL3RvZG8gKGludGVycHJldGVyICsgQU9UKSBhbmQKLy8gZXhhbXBsZXMvdG9kb19za2lhIChTa2lhKSBpbXBvcnQgaXQgZnJvbSB0aGVpciBvd24gdWkvdG9kby5zbGludCwgd2hpY2gKLy8gd3JhcHMgaXQgaW4gYSB3aW5kb3cgb2YgaXRzIG93bi4gTm90IGEgYnVpbGRfcnVubmVyIHNvdXJjZSBvZiB0aGlzIHBhY2thZ2U6Ci8vIGVhY2ggYXBwJ3MgZ2VuZXJhdGVkIHdyYXBwZXIgZW1iZWRzIGl0LCBhbmQgaXRzIEFPVCBidWlsZCBjb21waWxlcyBpdC4KaW1wb3J0IHsgQnV0dG9uLCBDaGVja0JveCwgTGluZUVkaXQsIExpc3RWaWV3LCBWZXJ0aWNhbEJveCwgSG9yaXpvbnRhbEJveCB9IGZyb20gInN0ZC13aWRnZXRzLnNsaW50IjsKCmV4cG9ydCBzdHJ1Y3QgVG9kb0l0ZW0gewogICAgdGl0bGU6IHN0cmluZywKICAgIGNoZWNrZWQ6IGJvb2wsCn0KCmV4cG9ydCBjb21wb25lbnQgVG9kb1ZpZXcgaW5oZXJpdHMgVmVydGljYWxCb3ggewogICAgaW4gcHJvcGVydHkgPFtUb2RvSXRlbV0+IHRvZG8tbW9kZWw7CgogICAgY2FsbGJhY2sgYWRkLXRvZG8odGl0bGU6IHN0cmluZyk7CiAgICBjYWxsYmFjayB0b2dnbGUtdG9kbyhpbmRleDogaW50LCBjaGVja2VkOiBib29sKTsKICAgIGNhbGxiYWNrIHJlbW92ZS1kb25lKCk7CgogICAgSG9yaXpvbnRhbEJveCB7CiAgICAgICAgcGFkZGluZzogMDsKICAgICAgICBlZGl0IDo9IExpbmVFZGl0IHsKICAgICAgICAgICAgcGxhY2Vob2xkZXItdGV4dDogIldoYXQgbmVlZHMgdG8gYmUgZG9uZT8iOwogICAgICAgICAgICBhY2NlcHRlZCh0ZXh0KSA9PiB7IHJvb3QuYWRkLXRvZG8odGV4dCk7IHNlbGYudGV4dCA9ICIiOyB9CiAgICAgICAgfQogICAgICAgIEJ1dHRvbiB7CiAgICAgICAgICAgIHRleHQ6ICJBZGQiOwogICAgICAgICAgICBwcmltYXJ5OiB0cnVlOwogICAgICAgICAgICBjbGlja2VkID0+IHsgcm9vdC5hZGQtdG9kbyhlZGl0LnRleHQpOyBlZGl0LnRleHQgPSAiIjsgfQogICAgICAgIH0KICAgIH0KICAgIExpc3RWaWV3IHsKICAgICAgICBmb3IgaXRlbVtpbmRleF0gaW4gcm9vdC50b2RvLW1vZGVsOiBIb3Jpem9udGFsQm94IHsKICAgICAgICAgICAgcGFkZGluZzogMDsKICAgICAgICAgICAgQ2hlY2tCb3ggewogICAgICAgICAgICAgICAgdGV4dDogaXRlbS50aXRsZTsKICAgICAgICAgICAgICAgIGNoZWNrZWQ6IGl0ZW0uY2hlY2tlZDsKICAgICAgICAgICAgICAgIHRvZ2dsZWQgPT4geyByb290LnRvZ2dsZS10b2RvKGluZGV4LCBzZWxmLmNoZWNrZWQpOyB9CiAgICAgICAgICAgIH0KICAgICAgICB9CiAgICB9CiAgICBCdXR0b24gewogICAgICAgIHRleHQ6ICJSZW1vdmUgZG9uZSBpdGVtcyI7CiAgICAgICAgY2xpY2tlZCA9PiB7IHJvb3QucmVtb3ZlLWRvbmUoKTsgfQogICAgfQp9Cg==",
};

/// `TodoItem`, a struct declared in `todo.slint`.
class TodoItem {
  const TodoItem({required this.checked, required this.title});

  /// Reads the value as the backends represent it.
  factory TodoItem.fromSlint(Map<Object?, Object?> value) => TodoItem(
    checked: value['checked'] as bool,
    title: value['title'] as String,
  );

  final bool checked;
  final String title;

  /// The representation the backends expect, keyed by the Slint field names.
  Map<String, Object?> toSlint() => {'checked': checked, 'title': title};

  TodoItem copyWith({bool? checked, String? title}) =>
      TodoItem(checked: checked ?? this.checked, title: title ?? this.title);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoItem && checked == other.checked && title == other.title;

  @override
  int get hashCode => Object.hash(checked, title);

  @override
  String toString() => 'TodoItem(checked: $checked, title: $title)';
}

/// Typed wrapper for the `TodoApp` component of `todo.slint`.
///
/// ```dart
/// final app = TodoApp(component); // a SlintComponent from any backend
/// ```
class TodoApp implements SlintSoftwareComponent {
  TodoApp(this.component);

  /// Name of the exported component this wrapper drives.
  static const componentName = 'TodoApp';

  /// The `.slint` source this wrapper was generated from.
  static const slintSource = _source;

  /// What [slintSource] reads besides itself, base64 by path relative to it.
  static const slintFiles = _files;

  /// Instantiates `TodoApp` through [factory].
  static TodoApp create(SlintComponentFactory factory) =>
      TodoApp(factory.instantiate(componentName));

  /// The backing instance, from any backend. App code goes through the typed
  /// members; the untyped bridge below is what the backends implement.
  final SlintComponent component;

  /// The target to hand a `SlintView`. Only a backend that renders in
  /// software has one; a texture backend (slint_skia) does not.
  @override
  SlintSoftwareRenderTarget get renderTarget => switch (component) {
    final SlintSoftwareComponent c => c.renderTarget,
    _ => throw StateError(
      '${component.runtimeType} does not render through a software target',
    ),
  };

  @override
  void dispose() => component.dispose();

  @override
  Object? getProperty(String name) => component.getProperty(name);

  @override
  void setProperty(String name, Object? value) =>
      component.setProperty(name, value);

  @override
  void setCallbackHandler(String name, SlintCallbackHandler handler) =>
      component.setCallbackHandler(name, handler);

  @override
  Object? invokeCallback(String name, List<Object?> arguments) =>
      component.invokeCallback(name, arguments);

  late final todoModel = SlintListModel<TodoItem>(
    () => component.getProperty('todo-model'),
    (value) => component.setProperty('todo-model', value),
    (e) => TodoItem.fromSlint(e as Map<Object?, Object?>),
    (e) => e.toSlint(),
  );

  /// Handles the `add-todo` callback; replaces any previous handler.
  void onAddTodo(void Function(String title) handler) =>
      component.setCallbackHandler('add-todo', (arguments) {
        handler(arguments[0] as String);
        return null;
      });

  /// Invokes the `add-todo` callback.
  void invokeAddTodo(String title) =>
      component.invokeCallback('add-todo', [title]);

  /// Handles the `remove-done` callback; replaces any previous handler.
  void onRemoveDone(void Function() handler) =>
      component.setCallbackHandler('remove-done', (arguments) {
        handler();
        return null;
      });

  /// Invokes the `remove-done` callback.
  void invokeRemoveDone() => component.invokeCallback('remove-done', []);

  /// Handles the `toggle-todo` callback; replaces any previous handler.
  void onToggleTodo(void Function(int index, bool checked) handler) =>
      component.setCallbackHandler('toggle-todo', (arguments) {
        handler((arguments[0] as num).toInt(), arguments[1] as bool);
        return null;
      });

  /// Invokes the `toggle-todo` callback.
  void invokeToggleTodo(int index, bool checked) =>
      component.invokeCallback('toggle-todo', [index, checked]);
}
