// GENERATED by slint_generator from todo.slint — do not edit.
// ignore_for_file: type=lint
library;

import 'package:slint/slint_core.dart';
import 'package:slint_generator/runtime.dart';

/// `todo.slint`, embedded so the interpreter can compile it at runtime.
///
/// Only the interpreter factory's construction names it, and in a build
/// that defaults to the AOT backend that is a const-dead branch, so the tree
/// shaker drops the string with it: the UI source is not in the shipped
/// binary.
const _source =
    "import { Button, CheckBox, LineEdit, ListView, VerticalBox, HorizontalBox } from \"std-widgets.slint\";\n\nexport struct TodoItem {\n    title: string,\n    checked: bool,\n}\n\nexport component TodoApp inherits Window {\n    preferred-width: 400px;\n    preferred-height: 600px;\n    title: \"Slint ♥ Flutter — Todo (Skia)\";\n\n    // Host (Dart) owns the list; this default renders before the host syncs.\n    in property <[TodoItem]> todo-model: [\n        { title: \"Wire Slint into Flutter\", checked: true },\n        { title: \"Render this list\", checked: false },\n    ];\n\n    // Named arguments carry through to the generated Dart signatures.\n    callback add-todo(title: string);\n    callback toggle-todo(index: int, checked: bool);\n    callback remove-done();\n\n    VerticalBox {\n        HorizontalBox {\n            padding: 0;\n            edit := LineEdit {\n                placeholder-text: \"What needs to be done?\";\n                accepted(text) => { root.add-todo(text); self.text = \"\"; }\n            }\n            Button {\n                text: \"Add\";\n                primary: true;\n                clicked => { root.add-todo(edit.text); edit.text = \"\"; }\n            }\n        }\n        ListView {\n            for item[index] in root.todo-model: HorizontalBox {\n                padding: 0;\n                CheckBox {\n                    text: item.title;\n                    checked: item.checked;\n                    toggled => { root.toggle-todo(index, self.checked); }\n                }\n            }\n        }\n        Button {\n            text: \"Remove done items\";\n            clicked => { root.remove-done(); }\n        }\n    }\n}\n";

/// `TodoItem`, a struct declared in `todo.slint`.
class TodoItem {
  const TodoItem({required this.checked, required this.title});

  /// Reads the value as the backends represent it.
  factory TodoItem.fromSlint(Map<Object?, Object?> value) => TodoItem(
    checked: value['checked'] as bool,
    title: value['title'] as String,
  );

  final bool checked;
  final String title;

  /// The representation the backends expect, keyed by the Slint field names.
  Map<String, Object?> toSlint() => {'checked': checked, 'title': title};

  TodoItem copyWith({bool? checked, String? title}) =>
      TodoItem(checked: checked ?? this.checked, title: title ?? this.title);

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TodoItem && checked == other.checked && title == other.title;

  @override
  int get hashCode => Object.hash(checked, title);

  @override
  String toString() => 'TodoItem(checked: $checked, title: $title)';
}

/// Typed wrapper for the `TodoApp` component of `todo.slint`.
///
/// ```dart
/// final app = TodoApp.create(SlintInterpreterFactory(TodoApp.slintSource));
/// ```
class TodoApp implements SlintSoftwareComponent {
  TodoApp(this.component);

  /// Name of the exported component this wrapper drives.
  static const componentName = 'TodoApp';

  /// The `.slint` source this wrapper was generated from.
  static const slintSource = _source;

  /// Instantiates `TodoApp` through [factory].
  static TodoApp create(SlintComponentFactory factory) =>
      TodoApp(factory.instantiate(componentName));

  /// The backing instance — use it for untyped property/callback access.
  final SlintSoftwareComponent component;

  @override
  SlintSoftwareRenderTarget get renderTarget => component.renderTarget;

  @override
  void dispose() => component.dispose();

  @override
  Object? getProperty(String name) => component.getProperty(name);

  @override
  void setProperty(String name, Object? value) =>
      component.setProperty(name, value);

  @override
  void setCallbackHandler(String name, SlintCallbackHandler handler) =>
      component.setCallbackHandler(name, handler);

  @override
  Object? invokeCallback(String name, List<Object?> arguments) =>
      component.invokeCallback(name, arguments);

  List<TodoItem> get todoModel => [
    for (final e in component.getProperty('todo-model') as List<Object?>)
      TodoItem.fromSlint(e as Map<Object?, Object?>),
  ];
  set todoModel(List<TodoItem> value) =>
      component.setProperty('todo-model', [for (final e in value) e.toSlint()]);

  /// Handles the `add-todo` callback; replaces any previous handler.
  void onAddTodo(void Function(String title) handler) =>
      component.setCallbackHandler('add-todo', (arguments) {
        handler(arguments[0] as String);
        return null;
      });

  /// Invokes the `add-todo` callback.
  void invokeAddTodo(String title) =>
      component.invokeCallback('add-todo', [title]);

  /// Handles the `remove-done` callback; replaces any previous handler.
  void onRemoveDone(void Function() handler) =>
      component.setCallbackHandler('remove-done', (arguments) {
        handler();
        return null;
      });

  /// Invokes the `remove-done` callback.
  void invokeRemoveDone() => component.invokeCallback('remove-done', []);

  /// Handles the `toggle-todo` callback; replaces any previous handler.
  void onToggleTodo(void Function(int index, bool checked) handler) =>
      component.setCallbackHandler('toggle-todo', (arguments) {
        handler((arguments[0] as num).toInt(), arguments[1] as bool);
        return null;
      });

  /// Invokes the `toggle-todo` callback.
  void invokeToggleTodo(int index, bool checked) =>
      component.invokeCallback('toggle-todo', [index, checked]);
}
