#ifndef SLINT_TESTING_FFI_H
#define SLINT_TESTING_FFI_H

/* GENERATED by cbindgen from src/lib.rs, do not edit. Regenerate: cd packages/slint_testing/rust && cbindgen --output include/slint_testing_ffi.h */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef void *SlintTestingApp;

/**
 * A host callback: `args_json` is the call's arguments as a JSON array,
 * valid only while it runs. The host reports a return value through
 * [slint_testing_callback_set_result] before returning; without one the
 * callback returns the declared type's default.
 */
typedef void (*SlintTestingCallbackFn)(void *user_data, const char *args_json);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Last error, or null. Caller frees with [slint_testing_string_free].
 */
char *slint_testing_last_error(void);

void slint_testing_string_free(char *s);

/**
 * Advances the testing backend's mock clock, driving animations and timers.
 */
void slint_testing_elapse_ms(uint64_t millis);

/**
 * Compiles `source` and instantiates `component` on the testing backend.
 * `component` may be null only when the source exports exactly one.
 */
SlintTestingApp slint_testing_app_new(const char *source, const char *path, const char *component);

void slint_testing_app_free(SlintTestingApp app);

/**
 * Runs a query and returns its matches as a JSON array of element
 * descriptors, replacing the previous snapshot. `kind` is one of `label`,
 * `id`, `type`, or `all`; `needle` is ignored for `all`.
 *
 * Caller frees with [slint_testing_string_free]; null means error.
 */
char *slint_testing_app_query(SlintTestingApp app, const char *kind, const char *needle);

/**
 * Invokes the accessible default action of the element at `index` in the
 * last query's snapshot — a button press, a checkbox toggle.
 */
bool slint_testing_app_click(SlintTestingApp app, uintptr_t index);

/**
 * Sets the accessible value of the element at `index` — typing into a text
 * input, moving a slider.
 */
bool slint_testing_app_set_value(SlintTestingApp app, uintptr_t index, const char *value);

/**
 * Property read; returns JSON. Caller frees with [slint_testing_string_free].
 */
char *slint_testing_app_get_property(SlintTestingApp app, const char *name);

bool slint_testing_app_set_property(SlintTestingApp app, const char *name, const char *json);

/**
 * Invokes a callback or function on the component; returns its result as
 * JSON. Caller frees with [slint_testing_string_free].
 */
char *slint_testing_app_invoke(SlintTestingApp app, const char *name, const char *args_json);

/**
 * Routes invocations of the callback `name` to `cb`, replacing whatever
 * handler the component had. `user_data` is handed back to `cb` untouched.
 */
bool slint_testing_app_set_callback(SlintTestingApp app,
                                    const char *name,
                                    SlintTestingCallbackFn cb,
                                    void *user_data);

/**
 * Sets the return value of the host callback running right now, as JSON.
 * Only meaningful from inside a [SlintTestingCallbackFn]; the string is
 * copied, so the caller keeps ownership. Null clears it.
 */
void slint_testing_callback_set_result(const char *json);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SLINT_TESTING_FFI_H */
