import 'dart:convert';

import 'package:slint_native/slint_native.dart';

/// Generates a `*.g.dart` file body for [source], a `.slint` document.
///
/// Compiles the source with the interpreter engine, introspects the exported
/// components, and emits one typed wrapper class per component. The `.slint`
/// source is embedded in the generated file and compiled at runtime by
/// `slint_native` — no Rust codegen involved.
Future<String> generateDart(String source, {required String sourceName}) async {
  final engine = NativeSlintEngine();
  try {
    final defs = await engine.compile(source, path: sourceName);
    final buffer = StringBuffer()
      ..writeln('// GENERATED by slint_compiler from $sourceName — do not edit.')
      ..writeln('//')
      ..writeln('// Regenerate with: dart run slint_compiler $sourceName')
      ..writeln('// ignore_for_file: type=lint')
      ..writeln()
      ..writeln("import 'package:slint/slint_core.dart';")
      ..writeln("import 'package:slint_native/slint_native.dart';")
      ..writeln()
      ..writeln('const String _slintSource = ${_dartStringLiteral(source)};');
    for (final def in defs) {
      _writeComponent(
        buffer,
        def as NativeSlintComponentDefinition,
        sourceName: sourceName,
      );
    }
    for (final def in defs) {
      def.dispose();
    }
    return buffer.toString();
  } finally {
    engine.dispose();
  }
}

void _writeComponent(
  StringBuffer b,
  NativeSlintComponentDefinition def, {
  required String sourceName,
}) {
  final name = def.name;
  final properties = def.properties();
  final callbacks = def.callbacks();

  b
    ..writeln()
    ..writeln('/// Typed wrapper for the `$name` component of `$sourceName`.')
    ..writeln('class $name implements SlintComponent {')
    ..writeln('  $name._(this._engine, this._component);')
    ..writeln()
    ..writeln('  final NativeSlintEngine _engine;')
    ..writeln('  final NativeSlintComponent _component;')
    ..writeln()
    ..writeln('  /// Compiles the embedded `.slint` source and instantiates `$name`.')
    ..writeln('  static Future<$name> create() async {')
    ..writeln('    final engine = NativeSlintEngine();')
    ..writeln('    try {')
    ..writeln("      final defs = await engine.compile(_slintSource, path: '$sourceName');")
    ..writeln('      final def = defs.firstWhere(')
    ..writeln("        (d) => d.name == '$name',")
    ..writeln("        orElse: () => throw StateError('component $name not found'),")
    ..writeln('      );')
    ..writeln('      final component = def.instantiate() as NativeSlintComponent;')
    ..writeln('      for (final d in defs) {')
    ..writeln('        d.dispose();')
    ..writeln('      }')
    ..writeln('      return $name._(engine, component);')
    ..writeln('    } catch (_) {')
    ..writeln('      engine.dispose();')
    ..writeln('      rethrow;')
    ..writeln('    }')
    ..writeln('  }')
    ..writeln()
    ..writeln('  /// The render target to plug into `SlintView`.')
    ..writeln('  NativeSoftwareRenderTarget get renderTarget => _component.renderTarget;');

  properties.forEach((propName, slintType) {
    final dart = _dartType(slintType);
    final getter = _camelCase(propName);
    b
      ..writeln()
      ..writeln('  /// `$propName` (Slint type: $slintType).')
      ..writeln('  ${dart.type} get $getter => ${dart.fromValue("_component.getProperty('$propName')")};')
      ..writeln('  set $getter(${dart.type} value) => _component.setProperty(\'$propName\', value);');
  });

  for (final cb in callbacks) {
    final pascal = _pascalCase(cb);
    b
      ..writeln()
      ..writeln('  /// Handles the `$cb` callback.')
      ..writeln('  void on$pascal(SlintCallbackHandler handler) =>')
      ..writeln("      _component.setCallbackHandler('$cb', handler);")
      ..writeln()
      ..writeln('  /// Invokes the `$cb` callback.')
      ..writeln('  Object? invoke$pascal([List<Object?> arguments = const []]) =>')
      ..writeln("      _component.invokeCallback('$cb', arguments);");
  }

  b
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Object? getProperty(String name) => _component.getProperty(name);')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  void setProperty(String name, Object? value) =>')
    ..writeln('      _component.setProperty(name, value);')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  void setCallbackHandler(String name, SlintCallbackHandler handler) =>')
    ..writeln('      _component.setCallbackHandler(name, handler);')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Object? invokeCallback(String name, List<Object?> arguments) =>')
    ..writeln('      _component.invokeCallback(name, arguments);')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  void dispose() {')
    ..writeln('    _component.dispose();')
    ..writeln('    _engine.dispose();')
    ..writeln('  }')
    ..writeln('}');
}

class _DartType {
  const _DartType(this.type, this._cast);
  final String type;
  final String? _cast;

  String fromValue(String expr) => switch (_cast) {
        null => expr,
        'double' => '($expr as num).toDouble()',
        final c => '$expr as $c',
      };
}

_DartType _dartType(String slintType) => switch (slintType) {
      'Number' => const _DartType('double', 'double'),
      'String' => const _DartType('String', 'String'),
      'Bool' => const _DartType('bool', 'bool'),
      'Model' => const _DartType('List<Object?>', 'List<Object?>'),
      'Struct' => const _DartType('Map<Object?, Object?>', 'Map<Object?, Object?>'),
      // Brush, Image, Void, enums, ... — passed through untyped.
      _ => const _DartType('Object?', null),
    };

String _camelCase(String kebab) {
  final parts = kebab.split('-').where((p) => p.isNotEmpty).toList();
  return parts.first +
      parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join();
}

String _pascalCase(String kebab) => kebab
    .split('-')
    .where((p) => p.isNotEmpty)
    .map((p) => p[0].toUpperCase() + p.substring(1))
    .join();

/// A Dart string literal for arbitrary content: JSON string escaping is a
/// subset of Dart's, leaving only `$` to neutralize.
String _dartStringLiteral(String value) =>
    jsonEncode(value).replaceAll(r'$', r'\$');
