import 'package:slint_generator/slint_generator.dart';

/// The AOT ABI contract shared by the Dart generator (this file), the Rust
/// glue generator (`rust_glue.dart`), and the build/link hooks
/// (`aot_build.dart` / `aot_link.dart`).

/// Per-component C entry points the glue exports, as `<prefix>_<op>`.
/// Must match the `#[no_mangle]` functions `rust_glue.dart` emits — a
/// generator test asserts they stay in sync.
const aotComponentOps = [
  'new',
  'free',
  'set_size',
  'render',
  'pointer_event',
  'key_event',
  'get_property',
  'set_property',
  'invoke',
  'set_callback',
];

/// C symbols shared by every component in the glue library.
const aotSharedSymbols = ['slint_aot_last_error', 'slint_aot_string_free'];

/// File name of the manifest the build hook writes next to the routed
/// staticlib for the link hook (components, symbols, linker flags).
const aotLinkManifestName = 'slint_aot_link.json';

/// Library name of the final linked dylib (`libslint_dart_aot.dylib` etc.).
const aotLibraryName = 'slint_dart_aot';

/// C symbol prefix for [componentName] (`TodoApp` → `slint_aot_todo_app`).
String aotSymbolPrefix(String componentName) =>
    'slint_aot_${snakeFromPascal(componentName)}';

/// All C symbols belonging to [componentName].
List<String> aotComponentSymbols(String componentName) =>
    [for (final op in aotComponentOps) '${aotSymbolPrefix(componentName)}_$op'];

/// Dart name of the generated `_new` extern for [componentName]. It carries
/// `@RecordUse()`, so tear-offs of it are what the link hook keys component
/// liveness on.
String aotNewExternName(String componentName) =>
    '_${_lowerName(componentName)}New';

String _lowerName(String pascal) =>
    camelCase(snakeFromPascal(pascal).replaceAll('_', '-'));

/// Generates the `.aot.g.dart` backend library for one `.slint` file.
///
/// Only the parts that must be per-file are generated: the `@Native` externs
/// for the AOT glue crate's per-component C symbols (they bind to this file's
/// `@DefaultAsset`) and one `SlintCompilerFactory` wiring them together.
/// Everything downstream of the ABI is hand-written in
/// `package:slint_compiler/runtime.dart`, and the typed API lives in the
/// sibling `.g.dart` wrapper generated by `slint_generator`, which takes that
/// factory.
///
/// [packageName] and [assetLibraryPath] form the code asset id
/// `package:<packageName>/<assetLibraryPath>`, which must match the asset the
/// hook emits; [assetLibraryPath] is this file's path relative to `lib/`
/// (e.g. `todo.aot.g.dart`).
String generateDartFromSchema(
  SlintSchema schema, {
  required String packageName,
  required String assetLibraryPath,
  required String sourceName,
}) {
  final b = StringBuffer('''
// GENERATED by slint_compiler from $sourceName — do not edit.
// ignore_for_file: type=lint
@ffi.DefaultAsset('package:$packageName/$assetLibraryPath')
library;

import 'dart:ffi' as ffi;

import 'package:meta/meta.dart' show RecordUse;
import 'package:slint_compiler/runtime.dart';

@ffi.Native<ffi.Pointer<ffi.Char> Function()>(symbol: 'slint_aot_last_error')
external ffi.Pointer<ffi.Char> _lastError();

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>(symbol: 'slint_aot_string_free')
external void _stringFree(ffi.Pointer<ffi.Char> s);
''');

  for (final component in schema.components) {
    b.write(_componentDart(component));
  }
  return b.toString();
}

String _componentDart(ComponentSchema component) {
  final pascal = component.name;
  final lower = _lowerName(pascal);
  final sym = aotSymbolPrefix(pascal);

  return '''

// === $pascal ===

// Liveness anchor: the factory below tears this off, so the AOT link hook
// sees a recorded use exactly when this component is reachable — and drops
// its native code from the dylib when it is not.
@RecordUse()
@ffi.Native<ffi.Pointer<ffi.Void> Function()>(symbol: '${sym}_new')
external ffi.Pointer<ffi.Void> _${lower}New();

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(symbol: '${sym}_free')
external void _${lower}Free(ffi.Pointer<ffi.Void> handle);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Uint32, ffi.Uint32)>(symbol: '${sym}_set_size')
external void _${lower}SetSize(ffi.Pointer<ffi.Void> handle, int width, int height);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Uint8>, ffi.Size)>(symbol: '${sym}_render')
external bool _${lower}Render(ffi.Pointer<ffi.Void> handle, ffi.Pointer<ffi.Uint8> buffer, int len);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Uint8, ffi.Float, ffi.Float, ffi.Uint8, ffi.Float, ffi.Float)>(symbol: '${sym}_pointer_event')
external void _${lower}PointerEvent(ffi.Pointer<ffi.Void> handle, int kind, double x, double y, int button, double dx, double dy);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Bool)>(symbol: '${sym}_key_event')
external void _${lower}KeyEvent(ffi.Pointer<ffi.Void> handle, ffi.Pointer<ffi.Char> text, bool pressed);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>(symbol: '${sym}_get_property')
external ffi.Pointer<ffi.Char> _${lower}GetProperty(ffi.Pointer<ffi.Void> handle, ffi.Pointer<ffi.Char> name);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>(symbol: '${sym}_set_property')
external bool _${lower}SetProperty(ffi.Pointer<ffi.Void> handle, ffi.Pointer<ffi.Char> name, ffi.Pointer<ffi.Char> json);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>(symbol: '${sym}_invoke')
external ffi.Pointer<ffi.Char> _${lower}Invoke(ffi.Pointer<ffi.Void> handle, ffi.Pointer<ffi.Char> name, ffi.Pointer<ffi.Char> argsJson);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.NativeFunction<SlintAotCallbackNative>>, ffi.Pointer<ffi.Void>)>(symbol: '${sym}_set_callback')
external bool _${lower}SetCallback(ffi.Pointer<ffi.Void> handle, ffi.Pointer<ffi.Char> name, ffi.Pointer<ffi.NativeFunction<SlintAotCallbackNative>> cb, ffi.Pointer<ffi.Void> userData);

/// AOT backend for `$pascal`: instantiates the slint-build compiled component
/// from the app's `slint-dart-aot` code asset, no interpreter involved.
///
/// Pass it to the generated wrapper: `$pascal.create(${aotFactoryName(pascal)})`
/// — or just `$pascal.create()`, which defaults to it in release builds.
final ${aotFactoryName(pascal)} = SlintCompilerFactory(
  componentName: '$pascal',
  ops: SlintComponentOps(
    lastError: _lastError,
    stringFree: _stringFree,
    create: _${lower}New,
    free: _${lower}Free,
    setSize: _${lower}SetSize,
    render: _${lower}Render,
    pointerEvent: _${lower}PointerEvent,
    keyEvent: _${lower}KeyEvent,
    getProperty: _${lower}GetProperty,
    setProperty: _${lower}SetProperty,
    invoke: _${lower}Invoke,
    setCallback: _${lower}SetCallback,
  ),
);
''';
}
