import 'names.dart';
import 'schema.dart';

/// Generates the `.g.dart` wrapper for one `.slint` file from its [schema].
///
/// The generated library binds (via `@Native`) to the per-component C symbols
/// of the AOT glue crate that the app's build hook compiles (see
/// `rust_glue.dart` / `aot_build.dart`) — no slint-interpreter at runtime.
///
/// [packageName] and [assetLibraryPath] form the code asset id
/// `package:<packageName>/<assetLibraryPath>`, which must match the asset the
/// hook emits; [assetLibraryPath] is the generated file's path relative to
/// `lib/` (e.g. `todo.g.dart`).
String generateDartFromSchema(
  SlintSchema schema, {
  required String packageName,
  required String assetLibraryPath,
  required String sourceName,
}) {
  final b = StringBuffer('''
// GENERATED by slint_compiler from $sourceName — do not edit.
// ignore_for_file: type=lint
@ffi.DefaultAsset('package:$packageName/$assetLibraryPath')
library;

import 'dart:convert';
import 'dart:ffi' as ffi;
import 'dart:typed_data';

import 'package:ffi/ffi.dart';
import 'package:slint/slint_core.dart';

typedef _CallbackNative = ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>);

@ffi.Native<ffi.Pointer<ffi.Char> Function()>(symbol: 'slint_aot_last_error')
external ffi.Pointer<ffi.Char> _lastError();

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>(symbol: 'slint_aot_string_free')
external void _stringFree(ffi.Pointer<ffi.Char> s);

String _takeError() {
  final p = _lastError();
  if (p.address == 0) return 'unknown error';
  return _readString(p);
}

String _readString(ffi.Pointer<ffi.Char> p) {
  final s = p.cast<Utf8>().toDartString();
  _stringFree(p);
  return s;
}

Object? _decode(String json) {
  if (json == 'null') return null;
  try {
    return jsonDecode(json);
  } catch (_) {
    return json;
  }
}

class _Ops {
  const _Ops({
    required this.free,
    required this.setSize,
    required this.render,
    required this.pointerEvent,
    required this.keyEvent,
    required this.getProp,
    required this.setProp,
    required this.invoke,
    required this.setCallback,
  });

  final void Function(ffi.Pointer<ffi.Void>) free;
  final void Function(ffi.Pointer<ffi.Void>, int, int) setSize;
  final bool Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Uint8>, int) render;
  final void Function(ffi.Pointer<ffi.Void>, int, double, double, int, double, double) pointerEvent;
  final void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, bool) keyEvent;
  final ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>) getProp;
  final bool Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>) setProp;
  final ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>) invoke;
  final bool Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.NativeFunction<_CallbackNative>>, ffi.Pointer<ffi.Void>) setCallback;
}

class _AotComponent implements SlintComponent {
  _AotComponent(this._handle, this._ops);

  final ffi.Pointer<ffi.Void> _handle;
  final _Ops _ops;
  final Map<String, ffi.NativeCallable<_CallbackNative>> _callbacks = {};
  bool _disposed = false;
  late final _AotRenderTarget renderTarget = _AotRenderTarget(this);

  @override
  Object? getProperty(String name) {
    final nameC = name.toNativeUtf8();
    try {
      final p = _ops.getProp(_handle, nameC.cast());
      if (p.address == 0) throw StateError(_takeError());
      return _decode(_readString(p));
    } finally {
      malloc.free(nameC);
    }
  }

  @override
  void setProperty(String name, Object? value) {
    final nameC = name.toNativeUtf8();
    final jsonC = jsonEncode(value).toNativeUtf8();
    try {
      if (!_ops.setProp(_handle, nameC.cast(), jsonC.cast())) {
        throw StateError(_takeError());
      }
    } finally {
      malloc.free(nameC);
      malloc.free(jsonC);
    }
  }

  @override
  void setCallbackHandler(String name, SlintCallbackHandler handler) {
    // Create the trampoline first; only close the old one after native code
    // has the new pointer, so a failed set cannot leave a dangling fn.
    final callable = ffi.NativeCallable<_CallbackNative>.isolateLocal(
      (ffi.Pointer<ffi.Void> userData, ffi.Pointer<ffi.Char> argsJson) {
        try {
          final args = jsonDecode(argsJson.cast<Utf8>().toDartString()) as List<dynamic>;
          // Handler return values ignored; Slint side gets the default value.
          handler(args);
        } catch (_) {}
      },
    );
    final nameC = name.toNativeUtf8();
    try {
      if (!_ops.setCallback(_handle, nameC.cast(), callable.nativeFunction, ffi.nullptr)) {
        callable.close();
        throw StateError(_takeError());
      }
    } finally {
      malloc.free(nameC);
    }
    _callbacks.remove(name)?.close();
    _callbacks[name] = callable;
  }

  @override
  Object? invokeCallback(String name, List<Object?> arguments) {
    final nameC = name.toNativeUtf8();
    final argsC = jsonEncode(arguments).toNativeUtf8();
    try {
      final p = _ops.invoke(_handle, nameC.cast(), argsC.cast());
      if (p.address == 0) throw StateError(_takeError());
      return _decode(_readString(p));
    } finally {
      malloc.free(nameC);
      malloc.free(argsC);
    }
  }

  @override
  void dispose() {
    if (_disposed) return;
    _disposed = true;
    _ops.free(_handle);
    for (final callable in _callbacks.values) {
      callable.close();
    }
    _callbacks.clear();
    renderTarget.dispose();
  }
}

class _AotRenderTarget implements SlintSoftwareRenderTarget {
  _AotRenderTarget(this._component) {
    _allocateBuffer();
  }

  final _AotComponent _component;
  ffi.Pointer<ffi.Uint8> _pixelBuffer = ffi.nullptr;
  Uint8List _pixels = Uint8List(0);
  int _width = 800;
  int _height = 600;
  bool _disposed = false;

  void _allocateBuffer() {
    final bufferSize = _width * _height * 4;
    _pixelBuffer = malloc<ffi.Uint8>(bufferSize);
    _pixels = _pixelBuffer.asTypedList(bufferSize);
  }

  @override
  SlintComponent get component => _component;

  @override
  int get width => _width;

  @override
  int get height => _height;

  @override
  void resize(int width, int height) {
    if (_disposed || (width == _width && height == _height)) return;
    if (_pixelBuffer.address != 0) {
      malloc.free(_pixelBuffer);
      _pixelBuffer = ffi.nullptr;
    }
    _width = width;
    _height = height;
    _allocateBuffer();
    _component._ops.setSize(_component._handle, width, height);
  }

  @override
  bool render() {
    if (_disposed || _pixelBuffer.address == 0) return false;
    return _component._ops.render(_component._handle, _pixelBuffer, _pixels.length);
  }

  @override
  void dispatchPointerEvent(SlintPointerEvent event) {
    _component._ops.pointerEvent(
      _component._handle,
      event.kind.index,
      event.x,
      event.y,
      event.button.index,
      event.scrollDeltaX,
      event.scrollDeltaY,
    );
  }

  @override
  void dispatchKeyEvent(SlintKeyEvent event) {
    final textC = event.text.toNativeUtf8();
    try {
      _component._ops.keyEvent(_component._handle, textC.cast(), event.pressed);
    } finally {
      malloc.free(textC);
    }
  }

  @override
  Uint8List get pixels => _pixels;

  @override
  void dispose() {
    if (_disposed) return;
    _disposed = true;
    if (_pixelBuffer.address != 0) {
      malloc.free(_pixelBuffer);
      _pixelBuffer = ffi.nullptr;
      _pixels = Uint8List(0);
    }
  }
}
''');

  for (final component in schema.components) {
    b.write(_componentDart(component));
  }
  return b.toString();
}

String _componentDart(ComponentSchema component) {
  final pascal = component.name;
  final lower = camelCase(snakeFromPascal(pascal).replaceAll('_', '-'));
  final sym = 'slint_aot_${snakeFromPascal(pascal)}';

  final members = StringBuffer();
  for (final prop in component.properties) {
    final name = camelCase(prop.name);
    final (dartType, getter) = switch (prop.type.kind) {
      'float' || 'length' || 'angle' || 'percent' || 'duration' => (
          'double',
          "(getProperty('${prop.name}') as num).toDouble()"
        ),
      'int' => ('int', "(getProperty('${prop.name}') as num).toInt()"),
      'string' => ('String', "getProperty('${prop.name}') as String"),
      'bool' => ('bool', "getProperty('${prop.name}') as bool"),
      'array' => (
          'List<Object?>',
          "getProperty('${prop.name}') as List<Object?>"
        ),
      'struct' => (
          'Map<Object?, Object?>',
          "getProperty('${prop.name}') as Map<Object?, Object?>"
        ),
      _ => throw StateError('unsupported property type: ${prop.type.kind}'),
    };
    members.write('''

  $dartType get $name => $getter;
  set $name($dartType value) => setProperty('${prop.name}', value);
''');
  }

  for (final cb in component.callbacks) {
    final p = pascalCase(cb.name);
    members.write('''

  void on$p(SlintCallbackHandler handler) => setCallbackHandler('${cb.name}', handler);
  Object? invoke$p([List<Object?> arguments = const []]) => invokeCallback('${cb.name}', arguments);
''');
  }

  return '''

// === $pascal ===

@ffi.Native<ffi.Pointer<ffi.Void> Function()>(symbol: '${sym}_new')
external ffi.Pointer<ffi.Void> _${lower}New();

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(symbol: '${sym}_free')
external void _${lower}Free(ffi.Pointer<ffi.Void> handle);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Uint32, ffi.Uint32)>(symbol: '${sym}_set_size')
external void _${lower}SetSize(ffi.Pointer<ffi.Void> handle, int width, int height);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Uint8>, ffi.Size)>(symbol: '${sym}_render')
external bool _${lower}Render(ffi.Pointer<ffi.Void> handle, ffi.Pointer<ffi.Uint8> buffer, int len);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Uint8, ffi.Float, ffi.Float, ffi.Uint8, ffi.Float, ffi.Float)>(symbol: '${sym}_pointer_event')
external void _${lower}PointerEvent(ffi.Pointer<ffi.Void> handle, int kind, double x, double y, int button, double dx, double dy);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Bool)>(symbol: '${sym}_key_event')
external void _${lower}KeyEvent(ffi.Pointer<ffi.Void> handle, ffi.Pointer<ffi.Char> text, bool pressed);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>(symbol: '${sym}_get_property')
external ffi.Pointer<ffi.Char> _${lower}GetProperty(ffi.Pointer<ffi.Void> handle, ffi.Pointer<ffi.Char> name);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>(symbol: '${sym}_set_property')
external bool _${lower}SetProperty(ffi.Pointer<ffi.Void> handle, ffi.Pointer<ffi.Char> name, ffi.Pointer<ffi.Char> json);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>(symbol: '${sym}_invoke')
external ffi.Pointer<ffi.Char> _${lower}Invoke(ffi.Pointer<ffi.Void> handle, ffi.Pointer<ffi.Char> name, ffi.Pointer<ffi.Char> argsJson);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.NativeFunction<_CallbackNative>>, ffi.Pointer<ffi.Void>)>(symbol: '${sym}_set_callback')
external bool _${lower}SetCallback(ffi.Pointer<ffi.Void> handle, ffi.Pointer<ffi.Char> name, ffi.Pointer<ffi.NativeFunction<_CallbackNative>> cb, ffi.Pointer<ffi.Void> userData);

final _Ops _${lower}Ops = _Ops(
  free: _${lower}Free,
  setSize: _${lower}SetSize,
  render: _${lower}Render,
  pointerEvent: _${lower}PointerEvent,
  keyEvent: _${lower}KeyEvent,
  getProp: _${lower}GetProperty,
  setProp: _${lower}SetProperty,
  invoke: _${lower}Invoke,
  setCallback: _${lower}SetCallback,
);

/// AOT-compiled `$pascal` — drives the slint-build generated component in
/// the app's `slint-dart-aot` code asset. No interpreter involved.
class $pascal extends _AotComponent {
  $pascal._(ffi.Pointer<ffi.Void> handle) : super(handle, _${lower}Ops);

  static Future<$pascal> create() async {
    final handle = _${lower}New();
    if (handle.address == 0) {
      throw StateError(_takeError());
    }
    return $pascal._(handle);
  }
$members}
''';
}
