import 'dart:convert';
import 'dart:ffi' as ffi;
import 'dart:typed_data';

import 'package:ffi/ffi.dart';
import 'package:slint/slint_core.dart';
import 'package:slint_generator/runtime.dart';

/// C signature of the callback trampoline the glue crate invokes.
typedef SlintAotCallbackNative = ffi.Void Function(
    ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>);

/// The C entry points of one AOT-compiled component.
///
/// A generated `*.aot.g.dart` declares the `@Native` externs — they must live
/// there, bound to that file's `@DefaultAsset` — and bundles them here, so
/// everything downstream of the ABI is written once, in this package.
final class SlintComponentOps {
  const SlintComponentOps({
    required this.lastError,
    required this.stringFree,
    required this.create,
    required this.free,
    required this.setSize,
    required this.render,
    required this.pointerEvent,
    required this.keyEvent,
    required this.getProperty,
    required this.setProperty,
    required this.invoke,
    required this.setCallback,
  });

  final ffi.Pointer<ffi.Char> Function() lastError;
  final void Function(ffi.Pointer<ffi.Char>) stringFree;
  final ffi.Pointer<ffi.Void> Function() create;
  final void Function(ffi.Pointer<ffi.Void>) free;
  final void Function(ffi.Pointer<ffi.Void>, int, int) setSize;
  final bool Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Uint8>, int) render;
  final void Function(
      ffi.Pointer<ffi.Void>, int, double, double, int, double, double)
      pointerEvent;
  final void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, bool)
      keyEvent;
  final ffi.Pointer<ffi.Char> Function(
      ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>) getProperty;
  final bool Function(
          ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      setProperty;
  final ffi.Pointer<ffi.Char> Function(
          ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
      invoke;
  final bool Function(
      ffi.Pointer<ffi.Void>,
      ffi.Pointer<ffi.Char>,
      ffi.Pointer<ffi.NativeFunction<SlintAotCallbackNative>>,
      ffi.Pointer<ffi.Void>) setCallback;

  /// Reads and frees the glue crate's thread-local error slot.
  String takeError() {
    final p = lastError();
    if (p.address == 0) return 'unknown error';
    return readString(p);
  }

  /// Copies a C string into Dart and frees the original.
  String readString(ffi.Pointer<ffi.Char> p) {
    final s = p.cast<Utf8>().toDartString();
    stringFree(p);
    return s;
  }
}

/// AOT backend for the wrappers generated by `slint_generator`: instantiates a
/// slint-build compiled component out of the app's own code asset, with no
/// slint-interpreter involved.
///
/// One instance per component, declared by the generated `*.aot.g.dart`:
///
/// ```dart
/// final app = TodoApp.create(todoAppFactory);
/// ```
final class SlintCompilerFactory extends SlintComponentFactory {
  const SlintCompilerFactory({required this.componentName, required this.ops});

  /// The single component this factory can instantiate.
  final String componentName;

  /// The C entry points backing [componentName].
  final SlintComponentOps ops;

  /// Needs no source — the component is already compiled into the code asset.
  @override
  SlintSoftwareComponent instantiate(String componentName) {
    if (componentName != this.componentName) {
      throw ArgumentError.value(
        componentName,
        'componentName',
        'this factory only instantiates ${this.componentName}',
      );
    }
    final handle = ops.create();
    if (handle.address == 0) {
      throw StateError(ops.takeError());
    }
    return _AotComponent(handle, ops);
  }
}

Object? _decode(String json) {
  if (json == 'null') return null;
  try {
    return jsonDecode(json);
  } catch (_) {
    return json;
  }
}

class _AotComponent implements SlintSoftwareComponent {
  _AotComponent(this._handle, this._ops);

  final ffi.Pointer<ffi.Void> _handle;
  final SlintComponentOps _ops;
  final Map<String, ffi.NativeCallable<SlintAotCallbackNative>> _callbacks = {};
  bool _disposed = false;

  @override
  late final _AotRenderTarget renderTarget = _AotRenderTarget(this);

  @override
  Object? getProperty(String name) {
    final nameC = name.toNativeUtf8();
    try {
      final p = _ops.getProperty(_handle, nameC.cast());
      if (p.address == 0) throw StateError(_ops.takeError());
      return _decode(_ops.readString(p));
    } finally {
      malloc.free(nameC);
    }
  }

  @override
  void setProperty(String name, Object? value) {
    final nameC = name.toNativeUtf8();
    final jsonC = jsonEncode(value).toNativeUtf8();
    try {
      if (!_ops.setProperty(_handle, nameC.cast(), jsonC.cast())) {
        throw StateError(_ops.takeError());
      }
    } finally {
      malloc.free(nameC);
      malloc.free(jsonC);
    }
  }

  @override
  void setCallbackHandler(String name, SlintCallbackHandler handler) {
    // Create the trampoline first; only close the old one after native code
    // has the new pointer, so a failed set cannot leave a dangling fn.
    final callable = ffi.NativeCallable<SlintAotCallbackNative>.isolateLocal(
      (ffi.Pointer<ffi.Void> userData, ffi.Pointer<ffi.Char> argsJson) {
        try {
          final args =
              jsonDecode(argsJson.cast<Utf8>().toDartString()) as List<dynamic>;
          // Handler return values ignored; Slint side gets the default value.
          handler(args);
        } catch (_) {}
      },
    );
    final nameC = name.toNativeUtf8();
    try {
      if (!_ops.setCallback(
          _handle, nameC.cast(), callable.nativeFunction, ffi.nullptr)) {
        callable.close();
        throw StateError(_ops.takeError());
      }
    } finally {
      malloc.free(nameC);
    }
    _callbacks.remove(name)?.close();
    _callbacks[name] = callable;
  }

  @override
  Object? invokeCallback(String name, List<Object?> arguments) {
    final nameC = name.toNativeUtf8();
    final argsC = jsonEncode(arguments).toNativeUtf8();
    try {
      final p = _ops.invoke(_handle, nameC.cast(), argsC.cast());
      if (p.address == 0) throw StateError(_ops.takeError());
      return _decode(_ops.readString(p));
    } finally {
      malloc.free(nameC);
      malloc.free(argsC);
    }
  }

  @override
  void dispose() {
    if (_disposed) return;
    _disposed = true;
    _ops.free(_handle);
    for (final callable in _callbacks.values) {
      callable.close();
    }
    _callbacks.clear();
    renderTarget.dispose();
  }
}

class _AotRenderTarget implements SlintSoftwareRenderTarget {
  _AotRenderTarget(this._component) {
    _allocateBuffer();
  }

  final _AotComponent _component;
  ffi.Pointer<ffi.Uint8> _pixelBuffer = ffi.nullptr;
  Uint8List _pixels = Uint8List(0);
  int _width = 800;
  int _height = 600;
  bool _disposed = false;

  void _allocateBuffer() {
    final bufferSize = _width * _height * 4;
    _pixelBuffer = malloc<ffi.Uint8>(bufferSize);
    _pixels = _pixelBuffer.asTypedList(bufferSize);
  }

  @override
  SlintComponent get component => _component;

  @override
  int get width => _width;

  @override
  int get height => _height;

  @override
  void resize(int width, int height) {
    if (_disposed || (width == _width && height == _height)) return;
    if (_pixelBuffer.address != 0) {
      malloc.free(_pixelBuffer);
      _pixelBuffer = ffi.nullptr;
    }
    _width = width;
    _height = height;
    _allocateBuffer();
    _component._ops.setSize(_component._handle, width, height);
  }

  @override
  bool render() {
    if (_disposed || _pixelBuffer.address == 0) return false;
    return _component._ops
        .render(_component._handle, _pixelBuffer, _pixels.length);
  }

  @override
  void dispatchPointerEvent(SlintPointerEvent event) {
    _component._ops.pointerEvent(
      _component._handle,
      event.kind.index,
      event.x,
      event.y,
      event.button.index,
      event.scrollDeltaX,
      event.scrollDeltaY,
    );
  }

  @override
  void dispatchKeyEvent(SlintKeyEvent event) {
    final textC = event.text.toNativeUtf8();
    try {
      _component._ops.keyEvent(_component._handle, textC.cast(), event.pressed);
    } finally {
      malloc.free(textC);
    }
  }

  @override
  Uint8List get pixels => _pixels;

  @override
  void dispose() {
    if (_disposed) return;
    _disposed = true;
    if (_pixelBuffer.address != 0) {
      malloc.free(_pixelBuffer);
      _pixelBuffer = ffi.nullptr;
      _pixels = Uint8List(0);
    }
  }
}
