import 'dart:io';

import 'names.dart';
import 'schema.dart';

/// The `slint` / `slint-build` version the generated crate pins. Must match
/// slint-introspect's `i-slint-compiler` pin (rust/Cargo.toml).
const slintVersion = '1.17.1';

/// One `.slint` source going into the AOT crate.
class SlintAotFile {
  SlintAotFile({required this.stem, required this.source, required this.schema});

  /// Unique file identifier (`lib/todo.slint` → `todo`); used for the copied
  /// source name and the generated Rust module file.
  final String stem;

  /// Contents of the `.slint` file.
  final String source;

  final SlintSchema schema;
}

/// Writes the generated AOT crate (`slint-dart-aot`) into [crateDir]:
/// `Cargo.toml`, `build.rs` (slint-build codegen), `src/lib.rs` (C ABI glue),
/// and `ui/<stem>.slint` copies. `target/` is left alone so cargo caching
/// survives regeneration.
void emitAotCrate(
  Directory crateDir, {
  required List<SlintAotFile> files,
  required String slintCoreCratePath,
}) {
  final ui = Directory('${crateDir.path}/ui');
  final src = Directory('${crateDir.path}/src');
  for (final d in [ui, src]) {
    if (d.existsSync()) d.deleteSync(recursive: true);
    d.createSync(recursive: true);
  }

  for (final f in files) {
    File('${ui.path}/${f.stem}.slint').writeAsStringSync(f.source);
  }

  File('${crateDir.path}/Cargo.toml').writeAsStringSync('''
# GENERATED by slint_compiler — do not edit.
[package]
name = "slint-dart-aot"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
slint = { version = "=$slintVersion", default-features = false, features = ["compat-1-2", "std", "renderer-software", "software-renderer-systemfonts"] }
slint-dart-core = { path = "${slintCoreCratePath.replaceAll(r'\', r'\\')}" }
serde_json = "1"

[build-dependencies]
slint-build = "=$slintVersion"

[profile.release]
panic = "unwind"
''');

  final compiles = files
      .map((f) => '''
    slint_build::compile_with_output_path(
        "ui/${f.stem}.slint",
        out.join("${f.stem}_slint.rs"),
        slint_build::CompilerConfiguration::new(),
    )
    .expect("slint-build failed for ui/${f.stem}.slint");''')
      .join('\n');
  File('${crateDir.path}/build.rs').writeAsStringSync('''
// GENERATED by slint_compiler — do not edit.
fn main() {
    let out = std::path::PathBuf::from(std::env::var_os("OUT_DIR").unwrap());
$compiles
}
''');

  File('${src.path}/lib.rs').writeAsStringSync(_libRs(files));
}

String _libRs(List<SlintAotFile> files) {
  final b = StringBuffer('''
//! GENERATED by slint_compiler — C ABI glue over slint-build generated
//! components. JSON value encoding mirrors slint-native-ffi.
#![allow(non_camel_case_types, unused_imports, unused_mut, unused_parens, clippy::all)]

use std::cell::RefCell;
use std::ffi::{c_char, c_void, CStr, CString};
use std::panic::catch_unwind;
use std::ptr;
use std::rc::Rc;

use serde_json::Value as Json;
use slint::platform::software_renderer::{
    MinimalSoftwareWindow, PremultipliedRgbaColor, RepaintBufferType,
};
use slint::{ComponentHandle, Model, ModelRc, PhysicalSize, SharedString, VecModel};

''');

  for (final f in files) {
    b.writeln('include!(concat!(env!("OUT_DIR"), "/${f.stem}_slint.rs"));');
  }

  b.write(r'''

thread_local! {
    static LAST_ERROR: RefCell<Option<String>> = RefCell::new(None);
    static NEXT_WINDOW: RefCell<Option<Rc<MinimalSoftwareWindow>>> = RefCell::new(None);
}

fn set_error(msg: String) {
    LAST_ERROR.with(|e| *e.borrow_mut() = Some(msg));
}

fn clear_error() {
    LAST_ERROR.with(|e| *e.borrow_mut() = None);
}

fn take_error() -> Option<String> {
    LAST_ERROR.with(|e| e.borrow_mut().take())
}

struct FlutterSoftwarePlatform;

impl slint::platform::Platform for FlutterSoftwarePlatform {
    fn create_window_adapter(
        &self,
    ) -> Result<Rc<dyn slint::platform::WindowAdapter>, slint::PlatformError> {
        let window = MinimalSoftwareWindow::new(RepaintBufferType::NewBuffer);
        NEXT_WINDOW.with(|slot| *slot.borrow_mut() = Some(window.clone()));
        Ok(window)
    }
}

fn ensure_platform_initialized() {
    // Err means a platform is already set — fine.
    let _ = slint::platform::set_platform(Box::new(FlutterSoftwarePlatform));
}

pub type SlintAotCallbackFn = extern "C" fn(user_data: *mut c_void, args_json: *const c_char);

fn json_number(v: &Json) -> Result<f64, String> {
    v.as_f64().ok_or_else(|| format!("expected number, got {v}"))
}

fn num_json(n: f64) -> Json {
    if n.fract() == 0.0 && n >= i64::MIN as f64 && n <= i64::MAX as f64 {
        Json::Number((n as i64).into())
    } else {
        serde_json::Number::from_f64(n).map(Json::Number).unwrap_or(Json::Null)
    }
}

fn cstr<'a>(p: *const c_char, what: &str) -> Result<&'a str, String> {
    if p.is_null() {
        return Err(format!("{what} is null"));
    }
    unsafe { CStr::from_ptr(p) }
        .to_str()
        .map_err(|_| format!("{what} is not valid UTF-8"))
}

fn json_out(v: Json) -> *mut c_char {
    match CString::new(v.to_string()) {
        Ok(c) => c.into_raw(),
        Err(_) => {
            set_error("output contains null byte".into());
            ptr::null_mut()
        }
    }
}

#[no_mangle]
pub extern "C" fn slint_aot_string_free(s: *mut c_char) {
    if !s.is_null() {
        let _ = catch_unwind(|| drop(unsafe { CString::from_raw(s) }));
    }
}

#[no_mangle]
pub extern "C" fn slint_aot_last_error() -> *mut c_char {
    match take_error() {
        Some(err) => CString::new(err).map(|c| c.into_raw()).unwrap_or(ptr::null_mut()),
        None => ptr::null_mut(),
    }
}
''');

  // Struct converters, deduplicated by struct name across all files.
  final structs = <String, TypeRef>{};
  for (final f in files) {
    for (final c in f.schema.components) {
      for (final p in c.properties) {
        _collectStructs(p.type, structs);
      }
      for (final cb in c.callbacks) {
        for (final a in cb.args) {
          _collectStructs(a, structs);
        }
        if (cb.returnType != null) _collectStructs(cb.returnType!, structs);
      }
    }
  }
  for (final s in structs.values) {
    b.write(_structHelpers(s));
  }

  final seenComponents = <String>{};
  for (final f in files) {
    for (final c in f.schema.components) {
      if (!seenComponents.add(c.name)) {
        throw StateError(
          'component ${c.name} is exported by more than one .slint file; '
          'component names must be unique across the package',
        );
      }
      b.write(_componentGlue(c));
    }
  }

  return b.toString();
}

void _collectStructs(TypeRef t, Map<String, TypeRef> out) {
  if (t.kind == 'struct') {
    out.putIfAbsent(t.structName!, () => t);
    for (final f in t.fields!) {
      _collectStructs(f.type, out);
    }
  } else if (t.kind == 'array') {
    _collectStructs(t.element!, out);
  }
}

/// Rust type of a schema type, as slint's Rust generator produces it.
String _rustType(TypeRef t) => switch (t.kind) {
      'float' || 'length' || 'angle' || 'percent' => 'f32',
      'duration' => 'i64',
      'int' => 'i32',
      'string' => 'SharedString',
      'bool' => 'bool',
      'struct' => rustIdent(t.structName!),
      'array' => 'ModelRc<${_rustType(t.element!)}>',
      _ => throw StateError('unsupported type kind: ${t.kind}'),
    };

/// Rust expression converting owned value [expr] of type [t] to `Json`.
String _toJson(String expr, TypeRef t) => switch (t.kind) {
      'float' || 'length' || 'angle' || 'percent' || 'duration' || 'int' =>
        'num_json(($expr) as f64)',
      'string' => 'Json::String(($expr).to_string())',
      'bool' => 'Json::Bool($expr)',
      'struct' => '${snakeFromPascal(t.structName!)}_to_json(&($expr))',
      'array' =>
        'Json::Array(($expr).iter().map(|x| ${_toJson('x', t.element!)}).collect::<Vec<_>>())',
      _ => throw StateError('unsupported type kind: ${t.kind}'),
    };

/// Rust expression (containing `?`) converting `&Json` [expr] to type [t].
String _fromJson(String expr, TypeRef t) => switch (t.kind) {
      'float' || 'length' || 'angle' || 'percent' => '(json_number($expr)? as f32)',
      'duration' => '(json_number($expr)? as i64)',
      'int' => '(json_number($expr)? as i32)',
      'string' =>
        'SharedString::from(($expr).as_str().ok_or_else(|| format!("expected string, got {}", $expr))?)',
      'bool' =>
        '($expr).as_bool().ok_or_else(|| format!("expected bool, got {}", $expr))?',
      'struct' => '${snakeFromPascal(t.structName!)}_from_json($expr)?',
      'array' => '''
{
        let arr = ($expr).as_array().ok_or_else(|| format!("expected array, got {}", $expr))?;
        let mut v: Vec<${_rustType(t.element!)}> = Vec::with_capacity(arr.len());
        for item in arr {
            v.push(${_fromJson('item', t.element!)});
        }
        ModelRc::new(VecModel::from(v))
    }''',
      _ => throw StateError('unsupported type kind: ${t.kind}'),
    };

String _structHelpers(TypeRef s) {
  final pascal = rustIdent(s.structName!);
  final snake = snakeFromPascal(s.structName!);
  final fromFields = s.fields!
      .map((f) => '''
    if let Some(f) = obj.get("${f.name}") {
        out.${rustIdent(f.name)} = ${_fromJson('f', f.type)};
    }''')
      .join('\n');
  final toFields = s.fields!
      .map((f) =>
          '    obj.insert("${f.name}".into(), ${_toJson('v.${rustIdent(f.name)}.clone()', f.type)});')
      .join('\n');
  return '''

fn ${snake}_from_json(v: &Json) -> Result<$pascal, String> {
    let obj = v.as_object().ok_or_else(|| format!("expected object for $pascal, got {v}"))?;
    let mut out = $pascal::default();
$fromFields
    Ok(out)
}

fn ${snake}_to_json(v: &$pascal) -> Json {
    let mut obj = serde_json::Map::new();
$toFields
    Json::Object(obj)
}
''';
}

String _componentGlue(ComponentSchema c) {
  final ty = rustIdent(c.name);
  final handle = '${ty}AotHandle';
  final p = 'slint_aot_${snakeFromPascal(c.name)}';

  final getArms = c.properties
      .map((prop) =>
          '            "${prop.name}" => Ok(${_toJson('handle.inst.get_${rustIdent(prop.name)}()', prop.type)}),')
      .join('\n');
  final setArms = c.properties
      .map((prop) => '''
            "${prop.name}" => {
                handle.inst.set_${rustIdent(prop.name)}(${_fromJson('&val', prop.type)});
                Ok(true)
            }''')
      .join('\n');

  final invokeArms = c.callbacks.map((cb) {
    final argLets = [
      for (var i = 0; i < cb.args.length; i++)
        '                let a$i = ${_fromJson('args.get($i).unwrap_or(&Json::Null)', cb.args[i])};',
    ].join('\n');
    final call =
        'handle.inst.invoke_${rustIdent(cb.name)}(${[for (var i = 0; i < cb.args.length; i++) 'a$i'].join(', ')})';
    final body = cb.returnType == null
        ? '                $call;\n                Ok(Json::Null)'
        : '                let r = $call;\n                Ok(${_toJson('r', cb.returnType!)})';
    return '''
            "${cb.name}" => {
$argLets
$body
            }''';
  }).join('\n');

  final callbackArms = c.callbacks.map((cb) {
    final params = [for (var i = 0; i < cb.args.length; i++) 'arg$i'].join(', ');
    final argsJson = [
      for (var i = 0; i < cb.args.length; i++) _toJson('arg$i', cb.args[i]),
    ].join(', ');
    final ret = cb.returnType == null ? '' : '\n                    Default::default()';
    return '''
            "${cb.name}" => {
                let ud = user_data as usize;
                handle.inst.on_${rustIdent(cb.name)}(move |$params| {
                    let args = Json::Array(vec![$argsJson]);
                    if let Ok(c) = CString::new(args.to_string()) {
                        cb(ud as *mut c_void, c.as_ptr());
                    }$ret
                });
                Ok(true)
            }''';
  }).join('\n');

  return '''

// === ${c.name} ===

struct $handle {
    inst: $ty,
    window: Rc<MinimalSoftwareWindow>,
}

#[no_mangle]
pub extern "C" fn ${p}_new() -> *mut c_void {
    clear_error();
    ensure_platform_initialized();
    match catch_unwind(|| -> Result<*mut c_void, String> {
        let inst = $ty::new().map_err(|e| format!("{e:?}"))?;
        inst.show().map_err(|e| format!("{e:?}"))?;
        let window = NEXT_WINDOW
            .with(|s| s.borrow_mut().take())
            .ok_or_else(|| "platform did not create a window".to_string())?;
        Ok(Box::into_raw(Box::new($handle { inst, window })) as *mut c_void)
    }) {
        Ok(Ok(ptr)) => ptr,
        Ok(Err(e)) => {
            set_error(e);
            ptr::null_mut()
        }
        Err(_) => {
            set_error("panicked in ${p}_new".into());
            ptr::null_mut()
        }
    }
}

#[no_mangle]
pub extern "C" fn ${p}_free(h: *mut c_void) {
    if !h.is_null() {
        let _ = catch_unwind(|| drop(unsafe { Box::from_raw(h as *mut $handle) }));
    }
}

#[no_mangle]
pub extern "C" fn ${p}_set_size(h: *mut c_void, width: u32, height: u32) {
    if h.is_null() {
        return;
    }
    let _ = catch_unwind(|| {
        let handle = unsafe { &*(h as *const $handle) };
        handle.window.set_size(PhysicalSize::new(width, height));
    });
}

#[no_mangle]
pub extern "C" fn ${p}_render(h: *mut c_void, buffer: *mut u8, len: usize) -> bool {
    clear_error();
    if h.is_null() || buffer.is_null() {
        return false;
    }
    match catch_unwind(|| {
        let handle = unsafe { &*(h as *const $handle) };
        let size = handle.window.size();
        let expected_len = (size.width as usize) * (size.height as usize) * 4;
        if len != expected_len {
            set_error(format!("buffer size mismatch: expected {expected_len}, got {len}"));
            return false;
        }
        let pixels = unsafe {
            std::slice::from_raw_parts_mut(buffer as *mut PremultipliedRgbaColor, len / 4)
        };
        slint::platform::update_timers_and_animations();
        let mut drawn = false;
        handle.window.draw_if_needed(|renderer| {
            renderer.render(pixels, size.width as usize);
            drawn = true;
        });
        drawn
    }) {
        Ok(result) => result,
        Err(_) => {
            set_error("panicked in ${p}_render".into());
            false
        }
    }
}

#[no_mangle]
pub extern "C" fn ${p}_pointer_event(
    h: *mut c_void,
    kind: u8,
    x: f32,
    y: f32,
    button: u8,
    dx: f32,
    dy: f32,
) {
    if h.is_null() {
        return;
    }
    let _ = catch_unwind(|| {
        if let Some(event) = slint_dart_core::events::pointer_event(kind, x, y, button, dx, dy) {
            let handle = unsafe { &*(h as *const $handle) };
            let _ = handle.window.dispatch_event(event);
        }
    });
}

#[no_mangle]
pub extern "C" fn ${p}_key_event(h: *mut c_void, text: *const c_char, pressed: bool) {
    if h.is_null() || text.is_null() {
        return;
    }
    let _ = catch_unwind(|| {
        if let Ok(text_str) = unsafe { CStr::from_ptr(text) }.to_str() {
            let event = slint_dart_core::events::key_event(text_str, pressed);
            let handle = unsafe { &*(h as *const $handle) };
            let _ = handle.window.dispatch_event(event);
        }
    });
}

#[no_mangle]
pub extern "C" fn ${p}_get_property(h: *mut c_void, name: *const c_char) -> *mut c_char {
    clear_error();
    if h.is_null() {
        return ptr::null_mut();
    }
    match catch_unwind(|| -> Result<Json, String> {
        let name = cstr(name, "property name")?;
        let handle = unsafe { &*(h as *const $handle) };
        match name {
$getArms
            _ => Err(format!("unknown property '{name}'")),
        }
    }) {
        Ok(Ok(v)) => json_out(v),
        Ok(Err(e)) => {
            set_error(e);
            ptr::null_mut()
        }
        Err(_) => {
            set_error("panicked in ${p}_get_property".into());
            ptr::null_mut()
        }
    }
}

#[no_mangle]
pub extern "C" fn ${p}_set_property(h: *mut c_void, name: *const c_char, json: *const c_char) -> bool {
    clear_error();
    if h.is_null() {
        return false;
    }
    match catch_unwind(|| -> Result<bool, String> {
        let name = cstr(name, "property name")?;
        let val: Json = serde_json::from_str(cstr(json, "property json")?)
            .map_err(|e| format!("invalid JSON for property '{name}': {e}"))?;
        let handle = unsafe { &*(h as *const $handle) };
        match name {
$setArms
            _ => Err(format!("unknown property '{name}'")),
        }
    }) {
        Ok(Ok(ok)) => ok,
        Ok(Err(e)) => {
            set_error(e);
            false
        }
        Err(_) => {
            set_error("panicked in ${p}_set_property".into());
            false
        }
    }
}

#[no_mangle]
pub extern "C" fn ${p}_invoke(h: *mut c_void, name: *const c_char, args_json: *const c_char) -> *mut c_char {
    clear_error();
    if h.is_null() {
        return ptr::null_mut();
    }
    match catch_unwind(|| -> Result<Json, String> {
        let name = cstr(name, "callback name")?;
        let args: Json = serde_json::from_str(cstr(args_json, "args json")?)
            .map_err(|e| format!("invalid args JSON for '{name}': {e}"))?;
        let args = args
            .as_array()
            .ok_or_else(|| "args_json must be a JSON array".to_string())?;
        let handle = unsafe { &*(h as *const $handle) };
        match name {
$invokeArms
            _ => Err(format!("unknown callback '{name}'")),
        }
    }) {
        Ok(Ok(v)) => json_out(v),
        Ok(Err(e)) => {
            set_error(e);
            ptr::null_mut()
        }
        Err(_) => {
            set_error("panicked in ${p}_invoke".into());
            ptr::null_mut()
        }
    }
}

#[no_mangle]
pub extern "C" fn ${p}_set_callback(
    h: *mut c_void,
    name: *const c_char,
    cb: SlintAotCallbackFn,
    user_data: *mut c_void,
) -> bool {
    clear_error();
    if h.is_null() {
        return false;
    }
    match catch_unwind(|| -> Result<bool, String> {
        let name = cstr(name, "callback name")?;
        let handle = unsafe { &*(h as *const $handle) };
        match name {
$callbackArms
            _ => Err(format!("unknown callback '{name}'")),
        }
    }) {
        Ok(Ok(ok)) => ok,
        Ok(Err(e)) => {
            set_error(e);
            false
        }
        Err(_) => {
            set_error("panicked in ${p}_set_callback".into());
            false
        }
    }
}
''';
}
