// dart format off
// ignore_for_file: type=lint

// AUTO GENERATED FILE, DO NOT EDIT.
// 
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset('package:slint_interpreter/src/bindings.g.dart')
library;

import 'dart:ffi' as ffi;
@ffi.Native<ffi.Uint32 Function(SlintInterpreterDefinitionList )>()
external int slint_interpreter_definitions_count(SlintInterpreterDefinitionList list,
);

@ffi.Native<ffi.Void Function(SlintInterpreterDefinitionList )>()
external void slint_interpreter_definitions_free(SlintInterpreterDefinitionList list,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(SlintInterpreterDefinitionList , ffi.Uint32 )>()
external ffi.Pointer<ffi.Char> slint_interpreter_definitions_name(SlintInterpreterDefinitionList list,
int index,
);

@ffi.Native<SlintInterpreterDefinitionList Function(SlintInterpreterEngine , ffi.Pointer<ffi.Char> , ffi.Pointer<ffi.Char> )>()
external SlintInterpreterDefinitionList slint_interpreter_engine_compile(SlintInterpreterEngine engine,
ffi.Pointer<ffi.Char> source,
ffi.Pointer<ffi.Char> path,
);

@ffi.Native<ffi.Void Function(SlintInterpreterEngine )>()
external void slint_interpreter_engine_free(SlintInterpreterEngine engine,
);

@ffi.Native<SlintInterpreterEngine Function()>()
external SlintInterpreterEngine slint_interpreter_engine_new();

@ffi.Native<ffi.Void Function(SlintInterpreterInstance )>()
external void slint_interpreter_instance_free(SlintInterpreterInstance instance,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(SlintInterpreterInstance , ffi.Pointer<ffi.Char> )>()
external ffi.Pointer<ffi.Char> slint_interpreter_instance_get_property(SlintInterpreterInstance instance,
ffi.Pointer<ffi.Char> name,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(SlintInterpreterInstance , ffi.Pointer<ffi.Char> , ffi.Pointer<ffi.Char> )>()
external ffi.Pointer<ffi.Char> slint_interpreter_instance_invoke(SlintInterpreterInstance instance,
ffi.Pointer<ffi.Char> name,
ffi.Pointer<ffi.Char> args_json,
);

@ffi.Native<ffi.Void Function(SlintInterpreterInstance , ffi.Pointer<ffi.Char> , ffi.Bool )>()
external void slint_interpreter_instance_key_event(SlintInterpreterInstance instance,
ffi.Pointer<ffi.Char> text,
bool pressed,
);

@ffi.Native<ffi.Void Function(SlintInterpreterInstance , ffi.Uint8 , ffi.Float , ffi.Float , ffi.Uint8 , ffi.Float , ffi.Float )>()
external void slint_interpreter_instance_pointer_event(SlintInterpreterInstance instance,
int kind,
double x,
double y,
int button,
double dx,
double dy,
);

/// Finds elements in this instance's accessibility tree and returns them as a
/// JSON array of descriptors — identity, accessible state, and geometry in
/// Slint logical pixels relative to the window.
/// 
/// `kind` is one of `label`, `id`, `type`, or `all`; `needle` carries the text
/// to match and may be null for `all`. This is what lets a test find a Slint
/// element and work out where to click it; the descriptors match the ones
/// `slint-testing-ffi` produces, because both come from `describe_all`.
/// 
/// Caller frees with [slint_interpreter_string_free]; null means error.
@ffi.Native<ffi.Pointer<ffi.Char> Function(SlintInterpreterInstance , ffi.Pointer<ffi.Char> , ffi.Pointer<ffi.Char> )>()
external ffi.Pointer<ffi.Char> slint_interpreter_instance_query_elements(SlintInterpreterInstance instance,
ffi.Pointer<ffi.Char> kind,
ffi.Pointer<ffi.Char> needle,
);

@ffi.Native<ffi.Bool Function(SlintInterpreterInstance , ffi.Pointer<ffi.Uint8> , ffi.UintPtr )>()
external bool slint_interpreter_instance_render(SlintInterpreterInstance instance,
ffi.Pointer<ffi.Uint8> buffer,
int len,
);

@ffi.Native<ffi.Bool Function(SlintInterpreterInstance , ffi.Pointer<ffi.Char> , SlintInterpreterCallbackFn , ffi.Pointer<ffi.Void> )>()
external bool slint_interpreter_instance_set_callback(SlintInterpreterInstance instance,
ffi.Pointer<ffi.Char> name,
SlintInterpreterCallbackFn cb,
ffi.Pointer<ffi.Void> user_data,
);

@ffi.Native<ffi.Bool Function(SlintInterpreterInstance , ffi.Pointer<ffi.Char> , ffi.Pointer<ffi.Char> )>()
external bool slint_interpreter_instance_set_property(SlintInterpreterInstance instance,
ffi.Pointer<ffi.Char> name,
ffi.Pointer<ffi.Char> json,
);

@ffi.Native<ffi.Void Function(SlintInterpreterInstance , ffi.Uint32 , ffi.Uint32 )>()
external void slint_interpreter_instance_set_size(SlintInterpreterInstance instance,
int width,
int height,
);

@ffi.Native<SlintInterpreterInstance Function(SlintInterpreterDefinitionList , ffi.Uint32 )>()
external SlintInterpreterInstance slint_interpreter_instantiate(SlintInterpreterDefinitionList list,
int index,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> slint_interpreter_last_error();

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char> )>()
external void slint_interpreter_string_free(ffi.Pointer<ffi.Char> s,
);

typedef SlintInterpreterCallbackFn = ffi.Pointer<ffi.NativeFunction<SlintInterpreterCallbackFnFunction>>;
typedef SlintInterpreterCallbackFnFunction = ffi.Void Function(ffi.Pointer<ffi.Void> user_data, ffi.Pointer<ffi.Char> args_json);
typedef DartSlintInterpreterCallbackFnFunction = void Function(ffi.Pointer<ffi.Void> user_data, ffi.Pointer<ffi.Char> args_json);
typedef SlintInterpreterDefinitionList = ffi.Pointer<ffi.Void>;
typedef SlintInterpreterEngine = ffi.Pointer<ffi.Void>;
typedef SlintInterpreterInstance = ffi.Pointer<ffi.Void>;
final class __arm_legacy_debug_state extends ffi.Struct{
@ffi.Array.multi([16])
  external ffi.Array<__uint32_t> __bvr;

@ffi.Array.multi([16])
  external ffi.Array<__uint32_t> __bcr;

@ffi.Array.multi([16])
  external ffi.Array<__uint32_t> __wvr;

@ffi.Array.multi([16])
  external ffi.Array<__uint32_t> __wcr;

}

final class __arm_pagein_state extends ffi.Struct{
  @ffi.Int()
  external int __pagein_error;

}

typedef __builtin_va_list = ffi.Pointer<ffi.Char>;
final class __darwin_arm_cpmu_state64 extends ffi.Struct{
@ffi.Array.multi([16])
  external ffi.Array<__uint64_t> __ctrs;

}

final class __darwin_arm_debug_state32 extends ffi.Struct{
@ffi.Array.multi([16])
  external ffi.Array<__uint32_t> __bvr;

@ffi.Array.multi([16])
  external ffi.Array<__uint32_t> __bcr;

@ffi.Array.multi([16])
  external ffi.Array<__uint32_t> __wvr;

@ffi.Array.multi([16])
  external ffi.Array<__uint32_t> __wcr;

  @__uint64_t()
  external int __mdscr_el1;

}

final class __darwin_arm_debug_state64 extends ffi.Struct{
@ffi.Array.multi([16])
  external ffi.Array<__uint64_t> __bvr;

@ffi.Array.multi([16])
  external ffi.Array<__uint64_t> __bcr;

@ffi.Array.multi([16])
  external ffi.Array<__uint64_t> __wvr;

@ffi.Array.multi([16])
  external ffi.Array<__uint64_t> __wcr;

  @__uint64_t()
  external int __mdscr_el1;

}

final class __darwin_arm_exception_state extends ffi.Struct{
  @__uint32_t()
  external int __exception;

  @__uint32_t()
  external int __fsr;

  @__uint32_t()
  external int __far;

}

final class __darwin_arm_exception_state64 extends ffi.Struct{
  @__uint64_t()
  external int __far;

  @__uint32_t()
  external int __esr;

  @__uint32_t()
  external int __exception;

}

final class __darwin_arm_exception_state64_v2 extends ffi.Struct{
  @__uint64_t()
  external int __far;

  @__uint64_t()
  external int __esr;

}

final class __darwin_arm_neon_state extends ffi.Opaque{
}

final class __darwin_arm_neon_state64 extends ffi.Opaque{
}

final class __darwin_arm_sme2_state extends ffi.Struct{
@ffi.Array.multi([64])
  external ffi.Array<ffi.Char> __zt0;

}

final class __darwin_arm_sme_state extends ffi.Struct{
  @__uint64_t()
  external int __svcr;

  @__uint64_t()
  external int __tpidr2_el0;

  @__uint16_t()
  external int __svl_b;

}

final class __darwin_arm_sme_za_state extends ffi.Struct{
@ffi.Array.multi([4096])
  external ffi.Array<ffi.Char> __za;

}

final class __darwin_arm_sve_p_state extends ffi.Struct{
@ffi.Array.multi([16, 32])
  external ffi.Array<ffi.Array<ffi.Char>> __p;

}

final class __darwin_arm_sve_z_state extends ffi.Struct{
@ffi.Array.multi([16, 256])
  external ffi.Array<ffi.Array<ffi.Char>> __z;

}

final class __darwin_arm_thread_state extends ffi.Struct{
@ffi.Array.multi([13])
  external ffi.Array<__uint32_t> __r;

  @__uint32_t()
  external int __sp;

  @__uint32_t()
  external int __lr;

  @__uint32_t()
  external int __pc;

  @__uint32_t()
  external int __cpsr;

}

final class __darwin_arm_thread_state64 extends ffi.Struct{
@ffi.Array.multi([29])
  external ffi.Array<__uint64_t> __x;

  @__uint64_t()
  external int __fp;

  @__uint64_t()
  external int __lr;

  @__uint64_t()
  external int __sp;

  @__uint64_t()
  external int __pc;

  @__uint32_t()
  external int __cpsr;

  @__uint32_t()
  external int __pad;

}

final class __darwin_arm_vfp_state extends ffi.Struct{
@ffi.Array.multi([64])
  external ffi.Array<__uint32_t> __r;

  @__uint32_t()
  external int __fpscr;

}

typedef __darwin_blkcnt_t = __int64_t;
typedef __darwin_blksize_t = __int32_t;
typedef __darwin_clock_t = ffi.UnsignedLong;
typedef Dart__darwin_clock_t = int;
typedef __darwin_ct_rune_t = ffi.Int;
typedef Dart__darwin_ct_rune_t = int;
typedef __darwin_dev_t = __int32_t;
typedef __darwin_fsblkcnt_t = ffi.UnsignedInt;
typedef Dart__darwin_fsblkcnt_t = int;
typedef __darwin_fsfilcnt_t = ffi.UnsignedInt;
typedef Dart__darwin_fsfilcnt_t = int;
typedef __darwin_gid_t = __uint32_t;
typedef __darwin_id_t = __uint32_t;
typedef __darwin_ino64_t = __uint64_t;
typedef __darwin_ino_t = __darwin_ino64_t;
typedef __darwin_intptr_t = ffi.Long;
typedef Dart__darwin_intptr_t = int;
typedef __darwin_mach_port_name_t = __darwin_natural_t;
typedef __darwin_mach_port_t = __darwin_mach_port_name_t;
typedef __darwin_mbstate_t = __mbstate_t;
final class __darwin_mcontext32 extends ffi.Struct{
  external __darwin_arm_exception_state __es;

  external __darwin_arm_thread_state __ss;

  external __darwin_arm_vfp_state __fs;

}

final class __darwin_mcontext64 extends ffi.Opaque{
}

typedef __darwin_mode_t = __uint16_t;
typedef __darwin_natural_t = ffi.UnsignedInt;
typedef Dart__darwin_natural_t = int;
typedef __darwin_nl_item = ffi.Int;
typedef Dart__darwin_nl_item = int;
typedef __darwin_off_t = __int64_t;
typedef __darwin_pid_t = __int32_t;
typedef __darwin_pthread_attr_t = _opaque_pthread_attr_t;
typedef __darwin_pthread_cond_t = _opaque_pthread_cond_t;
typedef __darwin_pthread_condattr_t = _opaque_pthread_condattr_t;
final class __darwin_pthread_handler_rec extends ffi.Struct{
  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> )>> __routine;

  external ffi.Pointer<ffi.Void> __arg;

  external ffi.Pointer<__darwin_pthread_handler_rec> __next;

}

typedef __darwin_pthread_key_t = ffi.UnsignedLong;
typedef Dart__darwin_pthread_key_t = int;
typedef __darwin_pthread_mutex_t = _opaque_pthread_mutex_t;
typedef __darwin_pthread_mutexattr_t = _opaque_pthread_mutexattr_t;
typedef __darwin_pthread_once_t = _opaque_pthread_once_t;
typedef __darwin_pthread_rwlock_t = _opaque_pthread_rwlock_t;
typedef __darwin_pthread_rwlockattr_t = _opaque_pthread_rwlockattr_t;
typedef __darwin_pthread_t = ffi.Pointer<_opaque_pthread_t>;
typedef __darwin_ptrdiff_t = ffi.Long;
typedef Dart__darwin_ptrdiff_t = int;
typedef __darwin_rune_t = __darwin_wchar_t;
final class __darwin_sigaltstack extends ffi.Struct{
  external ffi.Pointer<ffi.Void> ss_sp;

  @__darwin_size_t()
  external int ss_size;

  @ffi.Int()
  external int ss_flags;

}

typedef __darwin_sigset_t = __uint32_t;
typedef __darwin_size_t = ffi.UnsignedLong;
typedef Dart__darwin_size_t = int;
typedef __darwin_socklen_t = __uint32_t;
typedef __darwin_ssize_t = ffi.Long;
typedef Dart__darwin_ssize_t = int;
typedef __darwin_suseconds_t = __int32_t;
typedef __darwin_time_t = ffi.Long;
typedef Dart__darwin_time_t = int;
final class __darwin_ucontext extends ffi.Struct{
  @ffi.Int()
  external int uc_onstack;

  @__darwin_sigset_t()
  external int uc_sigmask;

  external __darwin_sigaltstack uc_stack;

  external ffi.Pointer<__darwin_ucontext> uc_link;

  @__darwin_size_t()
  external int uc_mcsize;

  external ffi.Pointer<__darwin_mcontext64> uc_mcontext;

}

typedef __darwin_uid_t = __uint32_t;
typedef __darwin_useconds_t = __uint32_t;
typedef __darwin_va_list = __builtin_va_list;
typedef __darwin_wchar_t = ffi.Int;
typedef Dart__darwin_wchar_t = int;
typedef __darwin_wctrans_t = ffi.Int;
typedef Dart__darwin_wctrans_t = int;
typedef __darwin_wctype_t = __uint32_t;
typedef __darwin_wint_t = ffi.Int;
typedef Dart__darwin_wint_t = int;
typedef __gnuc_va_list = __builtin_va_list;
typedef __int16_t = ffi.Short;
typedef Dart__int16_t = int;
typedef __int32_t = ffi.Int;
typedef Dart__int32_t = int;
typedef __int64_t = ffi.LongLong;
typedef Dart__int64_t = int;
typedef __int8_t = ffi.SignedChar;
typedef Dart__int8_t = int;
final class __mbstate_t extends ffi.Union{
@ffi.Array.multi([128])
  external ffi.Array<ffi.Char> __mbstate8;

  @ffi.LongLong()
  external int _mbstateL;

}

final class __sigaction extends ffi.Struct{
  external __sigaction_u __sigaction_u$1;

  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void> , ffi.Int , ffi.Int , ffi.Pointer<siginfo_t> , ffi.Pointer<ffi.Void> )>> sa_tramp;

  @sigset_t()
  external int sa_mask;

  @ffi.Int()
  external int sa_flags;

}

final class __sigaction_u extends ffi.Union{
  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int )>> __sa_handler;

  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int , ffi.Pointer<__siginfo> , ffi.Pointer<ffi.Void> )>> __sa_sigaction;

}

final class __siginfo extends ffi.Struct{
  @ffi.Int()
  external int si_signo;

  @ffi.Int()
  external int si_errno;

  @ffi.Int()
  external int si_code;

  @pid_t()
  external int si_pid;

  @uid_t()
  external int si_uid;

  @ffi.Int()
  external int si_status;

  external ffi.Pointer<ffi.Void> si_addr;

  external sigval si_value;

  @ffi.Long()
  external int si_band;

@ffi.Array.multi([7])
  external ffi.Array<ffi.UnsignedLong> __pad;

}

typedef __uint16_t = ffi.UnsignedShort;
typedef Dart__uint16_t = int;
typedef __uint32_t = ffi.UnsignedInt;
typedef Dart__uint32_t = int;
typedef __uint64_t = ffi.UnsignedLongLong;
typedef Dart__uint64_t = int;
typedef __uint8_t = ffi.UnsignedChar;
typedef Dart__uint8_t = int;
final class _malloc_zone_t extends ffi.Opaque{
}

final class _opaque_pthread_attr_t extends ffi.Struct{
  @ffi.Long()
  external int __sig;

@ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __opaque;

}

final class _opaque_pthread_cond_t extends ffi.Struct{
  @ffi.Long()
  external int __sig;

@ffi.Array.multi([40])
  external ffi.Array<ffi.Char> __opaque;

}

final class _opaque_pthread_condattr_t extends ffi.Struct{
  @ffi.Long()
  external int __sig;

@ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __opaque;

}

final class _opaque_pthread_mutex_t extends ffi.Struct{
  @ffi.Long()
  external int __sig;

@ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __opaque;

}

final class _opaque_pthread_mutexattr_t extends ffi.Struct{
  @ffi.Long()
  external int __sig;

@ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __opaque;

}

final class _opaque_pthread_once_t extends ffi.Struct{
  @ffi.Long()
  external int __sig;

@ffi.Array.multi([8])
  external ffi.Array<ffi.Char> __opaque;

}

final class _opaque_pthread_rwlock_t extends ffi.Struct{
  @ffi.Long()
  external int __sig;

@ffi.Array.multi([192])
  external ffi.Array<ffi.Char> __opaque;

}

final class _opaque_pthread_rwlockattr_t extends ffi.Struct{
  @ffi.Long()
  external int __sig;

@ffi.Array.multi([16])
  external ffi.Array<ffi.Char> __opaque;

}

final class _opaque_pthread_t extends ffi.Struct{
  @ffi.Long()
  external int __sig;

  external ffi.Pointer<__darwin_pthread_handler_rec> __cleanup_stack;

@ffi.Array.multi([8176])
  external ffi.Array<ffi.Char> __opaque;

}

typedef ct_rune_t = __darwin_ct_rune_t;
typedef dev_t = __darwin_dev_t;
final class div_t extends ffi.Struct{
  @ffi.Int()
  external int quot;

  @ffi.Int()
  external int rem;

 static ffi.Pointer<div_t> $allocate(
 ffi.Allocator $allocator, {
 required int quot,
 required int rem,
 }) => $allocator<div_t>()
 ..ref.quot = quot
 ..ref.rem = rem;

}

typedef id_t = __darwin_id_t;
typedef int_fast16_t = ffi.Int16;
typedef Dartint_fast16_t = int;
typedef int_fast32_t = ffi.Int32;
typedef Dartint_fast32_t = int;
typedef int_fast64_t = ffi.Int64;
typedef Dartint_fast64_t = int;
typedef int_fast8_t = ffi.Int8;
typedef Dartint_fast8_t = int;
typedef int_least16_t = ffi.Int16;
typedef Dartint_least16_t = int;
typedef int_least32_t = ffi.Int32;
typedef Dartint_least32_t = int;
typedef int_least64_t = ffi.Int64;
typedef Dartint_least64_t = int;
typedef int_least8_t = ffi.Int8;
typedef Dartint_least8_t = int;
typedef intmax_t = ffi.Long;
typedef Dartintmax_t = int;
final class ldiv_t extends ffi.Struct{
  @ffi.Long()
  external int quot;

  @ffi.Long()
  external int rem;

 static ffi.Pointer<ldiv_t> $allocate(
 ffi.Allocator $allocator, {
 required int quot,
 required int rem,
 }) => $allocator<ldiv_t>()
 ..ref.quot = quot
 ..ref.rem = rem;

}

final class lldiv_t extends ffi.Struct{
  @ffi.LongLong()
  external int quot;

  @ffi.LongLong()
  external int rem;

 static ffi.Pointer<lldiv_t> $allocate(
 ffi.Allocator $allocator, {
 required int quot,
 required int rem,
 }) => $allocator<lldiv_t>()
 ..ref.quot = quot
 ..ref.rem = rem;

}

typedef malloc_type_id_t = ffi.UnsignedLongLong;
typedef Dartmalloc_type_id_t = int;
typedef malloc_zone_t = _malloc_zone_t;
typedef mcontext_t = ffi.Pointer<__darwin_mcontext64>;
typedef mode_t = __darwin_mode_t;
typedef pid_t = __darwin_pid_t;
final class proc_rlimit_control_wakeupmon extends ffi.Struct{
  @ffi.Uint32()
  external int wm_flags;

  @ffi.Int32()
  external int wm_rate;

 static ffi.Pointer<proc_rlimit_control_wakeupmon> $allocate(
 ffi.Allocator $allocator, {
 required int wm_flags,
 required int wm_rate,
 }) => $allocator<proc_rlimit_control_wakeupmon>()
 ..ref.wm_flags = wm_flags
 ..ref.wm_rate = wm_rate;

}

typedef pthread_attr_t = __darwin_pthread_attr_t;
typedef register_t = ffi.Int64;
typedef Dartregister_t = int;
typedef rlim_t = __uint64_t;
final class rlimit extends ffi.Struct{
  @rlim_t()
  external int rlim_cur;

  @rlim_t()
  external int rlim_max;

 static ffi.Pointer<rlimit> $allocate(
 ffi.Allocator $allocator, {
 required int rlim_cur,
 required int rlim_max,
 }) => $allocator<rlimit>()
 ..ref.rlim_cur = rlim_cur
 ..ref.rlim_max = rlim_max;

}

typedef rune_t = __darwin_rune_t;
final class rusage extends ffi.Struct{
  external timeval ru_utime;

  external timeval ru_stime;

  @ffi.Long()
  external int ru_maxrss;

  @ffi.Long()
  external int ru_ixrss;

  @ffi.Long()
  external int ru_idrss;

  @ffi.Long()
  external int ru_isrss;

  @ffi.Long()
  external int ru_minflt;

  @ffi.Long()
  external int ru_majflt;

  @ffi.Long()
  external int ru_nswap;

  @ffi.Long()
  external int ru_inblock;

  @ffi.Long()
  external int ru_oublock;

  @ffi.Long()
  external int ru_msgsnd;

  @ffi.Long()
  external int ru_msgrcv;

  @ffi.Long()
  external int ru_nsignals;

  @ffi.Long()
  external int ru_nvcsw;

  @ffi.Long()
  external int ru_nivcsw;

}

typedef rusage_info_current = rusage_info_v6;
typedef rusage_info_t = ffi.Pointer<ffi.Void>;
final class rusage_info_v0 extends ffi.Struct{
@ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> ri_uuid;

  @ffi.Uint64()
  external int ri_user_time;

  @ffi.Uint64()
  external int ri_system_time;

  @ffi.Uint64()
  external int ri_pkg_idle_wkups;

  @ffi.Uint64()
  external int ri_interrupt_wkups;

  @ffi.Uint64()
  external int ri_pageins;

  @ffi.Uint64()
  external int ri_wired_size;

  @ffi.Uint64()
  external int ri_resident_size;

  @ffi.Uint64()
  external int ri_phys_footprint;

  @ffi.Uint64()
  external int ri_proc_start_abstime;

  @ffi.Uint64()
  external int ri_proc_exit_abstime;

}

final class rusage_info_v1 extends ffi.Struct{
@ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> ri_uuid;

  @ffi.Uint64()
  external int ri_user_time;

  @ffi.Uint64()
  external int ri_system_time;

  @ffi.Uint64()
  external int ri_pkg_idle_wkups;

  @ffi.Uint64()
  external int ri_interrupt_wkups;

  @ffi.Uint64()
  external int ri_pageins;

  @ffi.Uint64()
  external int ri_wired_size;

  @ffi.Uint64()
  external int ri_resident_size;

  @ffi.Uint64()
  external int ri_phys_footprint;

  @ffi.Uint64()
  external int ri_proc_start_abstime;

  @ffi.Uint64()
  external int ri_proc_exit_abstime;

  @ffi.Uint64()
  external int ri_child_user_time;

  @ffi.Uint64()
  external int ri_child_system_time;

  @ffi.Uint64()
  external int ri_child_pkg_idle_wkups;

  @ffi.Uint64()
  external int ri_child_interrupt_wkups;

  @ffi.Uint64()
  external int ri_child_pageins;

  @ffi.Uint64()
  external int ri_child_elapsed_abstime;

}

final class rusage_info_v2 extends ffi.Struct{
@ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> ri_uuid;

  @ffi.Uint64()
  external int ri_user_time;

  @ffi.Uint64()
  external int ri_system_time;

  @ffi.Uint64()
  external int ri_pkg_idle_wkups;

  @ffi.Uint64()
  external int ri_interrupt_wkups;

  @ffi.Uint64()
  external int ri_pageins;

  @ffi.Uint64()
  external int ri_wired_size;

  @ffi.Uint64()
  external int ri_resident_size;

  @ffi.Uint64()
  external int ri_phys_footprint;

  @ffi.Uint64()
  external int ri_proc_start_abstime;

  @ffi.Uint64()
  external int ri_proc_exit_abstime;

  @ffi.Uint64()
  external int ri_child_user_time;

  @ffi.Uint64()
  external int ri_child_system_time;

  @ffi.Uint64()
  external int ri_child_pkg_idle_wkups;

  @ffi.Uint64()
  external int ri_child_interrupt_wkups;

  @ffi.Uint64()
  external int ri_child_pageins;

  @ffi.Uint64()
  external int ri_child_elapsed_abstime;

  @ffi.Uint64()
  external int ri_diskio_bytesread;

  @ffi.Uint64()
  external int ri_diskio_byteswritten;

}

final class rusage_info_v3 extends ffi.Struct{
@ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> ri_uuid;

  @ffi.Uint64()
  external int ri_user_time;

  @ffi.Uint64()
  external int ri_system_time;

  @ffi.Uint64()
  external int ri_pkg_idle_wkups;

  @ffi.Uint64()
  external int ri_interrupt_wkups;

  @ffi.Uint64()
  external int ri_pageins;

  @ffi.Uint64()
  external int ri_wired_size;

  @ffi.Uint64()
  external int ri_resident_size;

  @ffi.Uint64()
  external int ri_phys_footprint;

  @ffi.Uint64()
  external int ri_proc_start_abstime;

  @ffi.Uint64()
  external int ri_proc_exit_abstime;

  @ffi.Uint64()
  external int ri_child_user_time;

  @ffi.Uint64()
  external int ri_child_system_time;

  @ffi.Uint64()
  external int ri_child_pkg_idle_wkups;

  @ffi.Uint64()
  external int ri_child_interrupt_wkups;

  @ffi.Uint64()
  external int ri_child_pageins;

  @ffi.Uint64()
  external int ri_child_elapsed_abstime;

  @ffi.Uint64()
  external int ri_diskio_bytesread;

  @ffi.Uint64()
  external int ri_diskio_byteswritten;

  @ffi.Uint64()
  external int ri_cpu_time_qos_default;

  @ffi.Uint64()
  external int ri_cpu_time_qos_maintenance;

  @ffi.Uint64()
  external int ri_cpu_time_qos_background;

  @ffi.Uint64()
  external int ri_cpu_time_qos_utility;

  @ffi.Uint64()
  external int ri_cpu_time_qos_legacy;

  @ffi.Uint64()
  external int ri_cpu_time_qos_user_initiated;

  @ffi.Uint64()
  external int ri_cpu_time_qos_user_interactive;

  @ffi.Uint64()
  external int ri_billed_system_time;

  @ffi.Uint64()
  external int ri_serviced_system_time;

}

final class rusage_info_v4 extends ffi.Struct{
@ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> ri_uuid;

  @ffi.Uint64()
  external int ri_user_time;

  @ffi.Uint64()
  external int ri_system_time;

  @ffi.Uint64()
  external int ri_pkg_idle_wkups;

  @ffi.Uint64()
  external int ri_interrupt_wkups;

  @ffi.Uint64()
  external int ri_pageins;

  @ffi.Uint64()
  external int ri_wired_size;

  @ffi.Uint64()
  external int ri_resident_size;

  @ffi.Uint64()
  external int ri_phys_footprint;

  @ffi.Uint64()
  external int ri_proc_start_abstime;

  @ffi.Uint64()
  external int ri_proc_exit_abstime;

  @ffi.Uint64()
  external int ri_child_user_time;

  @ffi.Uint64()
  external int ri_child_system_time;

  @ffi.Uint64()
  external int ri_child_pkg_idle_wkups;

  @ffi.Uint64()
  external int ri_child_interrupt_wkups;

  @ffi.Uint64()
  external int ri_child_pageins;

  @ffi.Uint64()
  external int ri_child_elapsed_abstime;

  @ffi.Uint64()
  external int ri_diskio_bytesread;

  @ffi.Uint64()
  external int ri_diskio_byteswritten;

  @ffi.Uint64()
  external int ri_cpu_time_qos_default;

  @ffi.Uint64()
  external int ri_cpu_time_qos_maintenance;

  @ffi.Uint64()
  external int ri_cpu_time_qos_background;

  @ffi.Uint64()
  external int ri_cpu_time_qos_utility;

  @ffi.Uint64()
  external int ri_cpu_time_qos_legacy;

  @ffi.Uint64()
  external int ri_cpu_time_qos_user_initiated;

  @ffi.Uint64()
  external int ri_cpu_time_qos_user_interactive;

  @ffi.Uint64()
  external int ri_billed_system_time;

  @ffi.Uint64()
  external int ri_serviced_system_time;

  @ffi.Uint64()
  external int ri_logical_writes;

  @ffi.Uint64()
  external int ri_lifetime_max_phys_footprint;

  @ffi.Uint64()
  external int ri_instructions;

  @ffi.Uint64()
  external int ri_cycles;

  @ffi.Uint64()
  external int ri_billed_energy;

  @ffi.Uint64()
  external int ri_serviced_energy;

  @ffi.Uint64()
  external int ri_interval_max_phys_footprint;

  @ffi.Uint64()
  external int ri_runnable_time;

}

final class rusage_info_v5 extends ffi.Struct{
@ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> ri_uuid;

  @ffi.Uint64()
  external int ri_user_time;

  @ffi.Uint64()
  external int ri_system_time;

  @ffi.Uint64()
  external int ri_pkg_idle_wkups;

  @ffi.Uint64()
  external int ri_interrupt_wkups;

  @ffi.Uint64()
  external int ri_pageins;

  @ffi.Uint64()
  external int ri_wired_size;

  @ffi.Uint64()
  external int ri_resident_size;

  @ffi.Uint64()
  external int ri_phys_footprint;

  @ffi.Uint64()
  external int ri_proc_start_abstime;

  @ffi.Uint64()
  external int ri_proc_exit_abstime;

  @ffi.Uint64()
  external int ri_child_user_time;

  @ffi.Uint64()
  external int ri_child_system_time;

  @ffi.Uint64()
  external int ri_child_pkg_idle_wkups;

  @ffi.Uint64()
  external int ri_child_interrupt_wkups;

  @ffi.Uint64()
  external int ri_child_pageins;

  @ffi.Uint64()
  external int ri_child_elapsed_abstime;

  @ffi.Uint64()
  external int ri_diskio_bytesread;

  @ffi.Uint64()
  external int ri_diskio_byteswritten;

  @ffi.Uint64()
  external int ri_cpu_time_qos_default;

  @ffi.Uint64()
  external int ri_cpu_time_qos_maintenance;

  @ffi.Uint64()
  external int ri_cpu_time_qos_background;

  @ffi.Uint64()
  external int ri_cpu_time_qos_utility;

  @ffi.Uint64()
  external int ri_cpu_time_qos_legacy;

  @ffi.Uint64()
  external int ri_cpu_time_qos_user_initiated;

  @ffi.Uint64()
  external int ri_cpu_time_qos_user_interactive;

  @ffi.Uint64()
  external int ri_billed_system_time;

  @ffi.Uint64()
  external int ri_serviced_system_time;

  @ffi.Uint64()
  external int ri_logical_writes;

  @ffi.Uint64()
  external int ri_lifetime_max_phys_footprint;

  @ffi.Uint64()
  external int ri_instructions;

  @ffi.Uint64()
  external int ri_cycles;

  @ffi.Uint64()
  external int ri_billed_energy;

  @ffi.Uint64()
  external int ri_serviced_energy;

  @ffi.Uint64()
  external int ri_interval_max_phys_footprint;

  @ffi.Uint64()
  external int ri_runnable_time;

  @ffi.Uint64()
  external int ri_flags;

}

final class rusage_info_v6 extends ffi.Struct{
@ffi.Array.multi([16])
  external ffi.Array<ffi.Uint8> ri_uuid;

  @ffi.Uint64()
  external int ri_user_time;

  @ffi.Uint64()
  external int ri_system_time;

  @ffi.Uint64()
  external int ri_pkg_idle_wkups;

  @ffi.Uint64()
  external int ri_interrupt_wkups;

  @ffi.Uint64()
  external int ri_pageins;

  @ffi.Uint64()
  external int ri_wired_size;

  @ffi.Uint64()
  external int ri_resident_size;

  @ffi.Uint64()
  external int ri_phys_footprint;

  @ffi.Uint64()
  external int ri_proc_start_abstime;

  @ffi.Uint64()
  external int ri_proc_exit_abstime;

  @ffi.Uint64()
  external int ri_child_user_time;

  @ffi.Uint64()
  external int ri_child_system_time;

  @ffi.Uint64()
  external int ri_child_pkg_idle_wkups;

  @ffi.Uint64()
  external int ri_child_interrupt_wkups;

  @ffi.Uint64()
  external int ri_child_pageins;

  @ffi.Uint64()
  external int ri_child_elapsed_abstime;

  @ffi.Uint64()
  external int ri_diskio_bytesread;

  @ffi.Uint64()
  external int ri_diskio_byteswritten;

  @ffi.Uint64()
  external int ri_cpu_time_qos_default;

  @ffi.Uint64()
  external int ri_cpu_time_qos_maintenance;

  @ffi.Uint64()
  external int ri_cpu_time_qos_background;

  @ffi.Uint64()
  external int ri_cpu_time_qos_utility;

  @ffi.Uint64()
  external int ri_cpu_time_qos_legacy;

  @ffi.Uint64()
  external int ri_cpu_time_qos_user_initiated;

  @ffi.Uint64()
  external int ri_cpu_time_qos_user_interactive;

  @ffi.Uint64()
  external int ri_billed_system_time;

  @ffi.Uint64()
  external int ri_serviced_system_time;

  @ffi.Uint64()
  external int ri_logical_writes;

  @ffi.Uint64()
  external int ri_lifetime_max_phys_footprint;

  @ffi.Uint64()
  external int ri_instructions;

  @ffi.Uint64()
  external int ri_cycles;

  @ffi.Uint64()
  external int ri_billed_energy;

  @ffi.Uint64()
  external int ri_serviced_energy;

  @ffi.Uint64()
  external int ri_interval_max_phys_footprint;

  @ffi.Uint64()
  external int ri_runnable_time;

  @ffi.Uint64()
  external int ri_flags;

  @ffi.Uint64()
  external int ri_user_ptime;

  @ffi.Uint64()
  external int ri_system_ptime;

  @ffi.Uint64()
  external int ri_pinstructions;

  @ffi.Uint64()
  external int ri_pcycles;

  @ffi.Uint64()
  external int ri_energy_nj;

  @ffi.Uint64()
  external int ri_penergy_nj;

  @ffi.Uint64()
  external int ri_secure_time_in_system;

  @ffi.Uint64()
  external int ri_secure_ptime_in_system;

  @ffi.Uint64()
  external int ri_neural_footprint;

  @ffi.Uint64()
  external int ri_lifetime_max_neural_footprint;

  @ffi.Uint64()
  external int ri_interval_max_neural_footprint;

@ffi.Array.multi([9])
  external ffi.Array<ffi.Uint64> ri_reserved;

}

typedef sig_atomic_t = ffi.Int;
typedef Dartsig_atomic_t = int;
typedef sig_t = ffi.Pointer<ffi.NativeFunction<sig_tFunction>>;
typedef sig_tFunction = ffi.Void Function(ffi.Int );
typedef Dartsig_tFunction = void Function(int );
final class sigaction extends ffi.Struct{
  external __sigaction_u __sigaction_u$1;

  @sigset_t()
  external int sa_mask;

  @ffi.Int()
  external int sa_flags;

}

final class sigevent extends ffi.Struct{
  @ffi.Int()
  external int sigev_notify;

  @ffi.Int()
  external int sigev_signo;

  external sigval sigev_value;

  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(sigval )>> sigev_notify_function;

  external ffi.Pointer<pthread_attr_t> sigev_notify_attributes;

}

typedef siginfo_t = __siginfo;
typedef sigset_t = __darwin_sigset_t;
final class sigstack extends ffi.Struct{
  external ffi.Pointer<ffi.Char> ss_sp;

  @ffi.Int()
  external int ss_onstack;

 static ffi.Pointer<sigstack> $allocate(
 ffi.Allocator $allocator, {
 required ffi.Pointer<ffi.Char> ss_sp,
 required int ss_onstack,
 }) => $allocator<sigstack>()
 ..ref.ss_sp = ss_sp
 ..ref.ss_onstack = ss_onstack;

}

final class sigval extends ffi.Union{
  @ffi.Int()
  external int sival_int;

  external ffi.Pointer<ffi.Void> sival_ptr;

}

final class sigvec extends ffi.Struct{
  external ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int )>> sv_handler;

  @ffi.Int()
  external int sv_mask;

  @ffi.Int()
  external int sv_flags;

 static ffi.Pointer<sigvec> $allocate(
 ffi.Allocator $allocator, {
 required ffi.Pointer<ffi.NativeFunction<ffi.Void Function(ffi.Int )>> sv_handler,
 required int sv_mask,
 required int sv_flags,
 }) => $allocator<sigvec>()
 ..ref.sv_handler = sv_handler
 ..ref.sv_mask = sv_mask
 ..ref.sv_flags = sv_flags;

}

typedef stack_t = __darwin_sigaltstack;
typedef syscall_arg_t = u_int64_t;
final class timeval extends ffi.Struct{
  @__darwin_time_t()
  external int tv_sec;

  @__darwin_suseconds_t()
  external int tv_usec;

 static ffi.Pointer<timeval> $allocate(
 ffi.Allocator $allocator, {
 required int tv_sec,
 required int tv_usec,
 }) => $allocator<timeval>()
 ..ref.tv_sec = tv_sec
 ..ref.tv_usec = tv_usec;

}

typedef u_int16_t = ffi.UnsignedShort;
typedef Dartu_int16_t = int;
typedef u_int32_t = ffi.UnsignedInt;
typedef Dartu_int32_t = int;
typedef u_int64_t = ffi.UnsignedLongLong;
typedef Dartu_int64_t = int;
typedef u_int8_t = ffi.UnsignedChar;
typedef Dartu_int8_t = int;
typedef ucontext_t = __darwin_ucontext;
typedef uid_t = __darwin_uid_t;
typedef uint_fast16_t = ffi.Uint16;
typedef Dartuint_fast16_t = int;
typedef uint_fast32_t = ffi.Uint32;
typedef Dartuint_fast32_t = int;
typedef uint_fast64_t = ffi.Uint64;
typedef Dartuint_fast64_t = int;
typedef uint_fast8_t = ffi.Uint8;
typedef Dartuint_fast8_t = int;
typedef uint_least16_t = ffi.Uint16;
typedef Dartuint_least16_t = int;
typedef uint_least32_t = ffi.Uint32;
typedef Dartuint_least32_t = int;
typedef uint_least64_t = ffi.Uint64;
typedef Dartuint_least64_t = int;
typedef uint_least8_t = ffi.Uint8;
typedef Dartuint_least8_t = int;
typedef uintmax_t = ffi.UnsignedLong;
typedef Dartuintmax_t = int;
typedef user_addr_t = u_int64_t;
typedef user_long_t = ffi.Int64;
typedef Dartuser_long_t = int;
typedef user_off_t = ffi.Int64;
typedef Dartuser_off_t = int;
typedef user_size_t = u_int64_t;
typedef user_ssize_t = ffi.Int64;
typedef Dartuser_ssize_t = int;
typedef user_time_t = ffi.Int64;
typedef Dartuser_time_t = int;
typedef user_ulong_t = u_int64_t;
typedef va_list = __builtin_va_list;
final class wait extends ffi.Opaque{
}

