import 'package:slint/slint_core.dart';
import 'package:slint_generator/runtime.dart';

import 'interpreter_engine.dart';

/// Interpreter backend for the wrappers generated by `slint_generator`:
/// compiles [source] — the `.slint` the wrapper embeds — at runtime.
///
/// ```dart
/// final app = TodoApp.create(
///     SlintInterpreterFactory(TodoApp.slintSource, files: TodoApp.slintFiles));
/// ```
final class SlintInterpreterFactory extends SlintComponentFactory {
  /// Uses [engine] when given — otherwise creates (and owns) one.
  SlintInterpreterFactory(
    this.source, {
    this.files = const {},
    InterpreterSlintEngine? engine,
  }) : _engine = engine ?? InterpreterSlintEngine(),
       _ownsEngine = engine == null;

  /// The `.slint` source every [instantiate] compiles.
  final String source;

  /// What [source] reads besides itself — `import`ed `.slint` files and
  /// `@image-url` resources — base64 by path relative to it, as a generated
  /// wrapper's `slintFiles` holds them. The compiler resolves both from disk,
  /// so they are written out once, on first use.
  final Map<String, String> files;

  SlintSourceTree? _tree;

  String? get _compilePath {
    if (files.isEmpty) return null;
    return (_tree ??= writeSlintTree(source, files)).path;
  }

  final InterpreterSlintEngine _engine;
  final bool _ownsEngine;

  @override
  SlintSoftwareComponent instantiate(String componentName) {
    final defs = _engine.compile(
      source,
      path: _compilePath ?? '$componentName.slint',
    );
    try {
      for (final def in defs) {
        if (def.name == componentName) {
          return def.instantiate();
        }
      }
      throw StateError(
        "no component named '$componentName' in the compiled source "
        '(found: ${defs.map((d) => d.name).join(', ')})',
      );
    } finally {
      for (final def in defs) {
        def.dispose();
      }
    }
  }

  /// Frees the engine and any temporary source tree, if this factory created
  /// them. Components already instantiated keep working; dispose them
  /// separately.
  void dispose() {
    _tree?.dispose();
    _tree = null;
    if (_ownsEngine) {
      _engine.dispose();
    }
  }
}
