import 'dart:io';

import 'package:slint_generator/slint_generator.dart';

/// The `slint` / `slint-build` version the generated crate pins. Must match
/// the workspace pin in the root `Cargo.toml` (`[workspace.dependencies]`),
/// which slint-introspect and the FFI crates inherit.
const slintVersion = '1.17.1';

/// One `.slint` source going into the AOT crate.
class SlintAotFile {
  SlintAotFile({required this.stem, required this.path, required this.schema});

  /// Unique file identifier (`ui/todo.slint` → `todo`); names the generated
  /// Rust module file.
  final String stem;

  /// Absolute path of the `.slint` file. slint-build compiles it in place, so
  /// its relative `import`s and `@image-url`s resolve.
  final String path;

  final SlintSchema schema;
}

/// Writes the generated AOT crate (`slint-dart-aot`) into [crateDir]:
/// `Cargo.toml`, `build.rs` (slint-build codegen of each `.slint` in place,
/// rerun when it or anything it reads changes), and `src/lib.rs` (C ABI
/// glue). `target/` is left alone so cargo caching survives regeneration.
void emitAotCrate(
  Directory crateDir, {
  required List<SlintAotFile> files,
  required String slintCoreCratePath,
  File? lockfile,
}) {
  // The crate is its own workspace, so without a seed every machine resolves
  // its dependency tree afresh. Cargo keeps whatever versions in a lockfile
  // still satisfy the manifest, so the workspace's lock makes the AOT build
  // pick the same tree as the interpreter crates.
  if (lockfile != null && lockfile.existsSync()) {
    // The shared output dir is fresh on a clean machine (CI): without this,
    // `copySync` throws `PathNotFoundException` for the missing parent.
    // A missing lock needs nothing: cargo resolves afresh.
    crateDir.createSync(recursive: true);
    lockfile.copySync(File.fromUri(crateDir.uri.resolve('Cargo.lock')).path);
  }
  final src = Directory('${crateDir.path}/src');
  if (src.existsSync()) src.deleteSync(recursive: true);
  src.createSync(recursive: true);

  File('${crateDir.path}/Cargo.toml').writeAsStringSync('''
# GENERATED by slint_compiler — do not edit.
[package]
name = "slint-dart-aot"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[lib]
# Intermediate only: the app's link hook (slint_compiler/aot_link.dart) links
# the final dylib from this archive, dropping components no reachable Dart
# code uses (per @RecordUse recordings).
crate-type = ["staticlib"]

[dependencies]
slint = { version = "=$slintVersion", default-features = false, features = ["compat-1-2", "std", "renderer-software", "software-renderer-systemfonts"] }
slint-dart-core = { path = "${slintCoreCratePath.replaceAll(r'\', r'\\')}" }
serde_json = "1"

[build-dependencies]
slint-build = "=$slintVersion"

[profile.release]
# Load-bearing: the glue wraps every entry point in catch_unwind to turn a
# Slint panic into a Dart-visible error. "abort" would kill the host process.
panic = "unwind"
# The linked dylib ships in the app bundle, so size matters. Measured on the
# example (per-arch, aarch64): 13M default -> 9.3M with LTO + stripping.
#
# opt-level stays at the release default of 3. "z" is ~2M smaller but
# de-vectorises the software renderer's pixel loops, which are the hot path:
# a full 800x600 repaint went from 399us to 1075us (2.7x) on the example.
lto = "fat"
codegen-units = 1
# No `strip` here: the archive must keep its symbols for the link hook's
# tree-shaking link, which strips the final dylib instead.
''');

  final compiles = files
      .map(
        (f) =>
            '''
    let deps = slint_build::compile_with_output_path(
        r#"${f.path}"#,
        out.join("${f.stem}_slint.rs"),
        slint_build::CompilerConfiguration::new(),
    )
    .expect(r#"slint-build failed for ${f.path}"#);
    println!(r#"cargo:rerun-if-changed=${f.path}"#);
    for dep in deps {
        println!("cargo:rerun-if-changed={}", dep.display());
    }''',
      )
      .join('\n');
  File('${crateDir.path}/build.rs').writeAsStringSync('''
// GENERATED by slint_compiler — do not edit.
fn main() {
    let out = std::path::PathBuf::from(std::env::var_os("OUT_DIR").unwrap());
$compiles
}
''');

  File('${src.path}/lib.rs').writeAsStringSync(_libRs(files));
}

String _libRs(List<SlintAotFile> files) {
  final b = StringBuffer('''
//! GENERATED by slint_compiler — C ABI glue over slint-build generated
//! components. JSON value encoding mirrors slint-interpreter-ffi.
#![allow(non_camel_case_types, unused_imports, unused_mut, unused_parens, clippy::all)]

use std::cell::RefCell;
use std::ffi::{c_char, c_void, CStr, CString};
use std::panic::catch_unwind;
use std::ptr;
use std::rc::Rc;

use serde_json::Value as Json;
use slint::platform::software_renderer::{
    MinimalSoftwareWindow, PremultipliedRgbaColor, RepaintBufferType,
};
use slint::{Brush, Color, ComponentHandle, Image, Model, ModelRc, PhysicalSize, SharedString, VecModel};

''');

  for (final f in files) {
    b.writeln('include!(concat!(env!("OUT_DIR"), "/${f.stem}_slint.rs"));');
  }

  b.write(r'''

thread_local! {
    static LAST_ERROR: RefCell<Option<String>> = RefCell::new(None);
    static NEXT_WINDOW: RefCell<Option<Rc<MinimalSoftwareWindow>>> = RefCell::new(None);
    // Return value of the host callback running right now, handed over by
    // slint_aot_callback_set_result; cleared before each call, taken after.
    static CALLBACK_RESULT: RefCell<Option<String>> = RefCell::new(None);
}

fn set_error(msg: String) {
    LAST_ERROR.with(|e| *e.borrow_mut() = Some(msg));
}

fn clear_error() {
    LAST_ERROR.with(|e| *e.borrow_mut() = None);
}

fn take_error() -> Option<String> {
    LAST_ERROR.with(|e| e.borrow_mut().take())
}

/// See `slint_dart_core::thread`: false (with the error set) off the owning thread.
fn on_owner_thread() -> bool {
    match slint_dart_core::thread::check() {
        Ok(()) => true,
        Err(e) => {
            set_error(e);
            false
        }
    }
}

struct FlutterSoftwarePlatform;

impl slint::platform::Platform for FlutterSoftwarePlatform {
    fn create_window_adapter(
        &self,
    ) -> Result<Rc<dyn slint::platform::WindowAdapter>, slint::PlatformError> {
        let window = MinimalSoftwareWindow::new(RepaintBufferType::NewBuffer);
        NEXT_WINDOW.with(|slot| *slot.borrow_mut() = Some(window.clone()));
        Ok(window)
    }
}

fn ensure_platform_initialized() {
    // Err means a platform is already set — fine.
    let _ = slint::platform::set_platform(Box::new(FlutterSoftwarePlatform));
}

pub type SlintAotCallbackFn = extern "C" fn(user_data: *mut c_void, args_json: *const c_char);

fn json_number(v: &Json) -> Result<f64, String> {
    v.as_f64().ok_or_else(|| format!("expected number, got {v}"))
}

fn num_json(n: f64) -> Json {
    if n.fract() == 0.0 && n >= i64::MIN as f64 && n <= i64::MAX as f64 {
        Json::Number((n as i64).into())
    } else {
        serde_json::Number::from_f64(n).map(Json::Number).unwrap_or(Json::Null)
    }
}

fn parse_color_literal(s: &str) -> Option<Color> {
    let h = s.strip_prefix('#')?;
    match h.len() {
        6 => {
            let rgb = u32::from_str_radix(h, 16).ok()?;
            Some(Color::from_argb_encoded(0xff000000 | rgb))
        }
        8 => Some(Color::from_argb_encoded(u32::from_str_radix(h, 16).ok()?)),
        _ => None,
    }
}

fn color_to_json(c: &Color) -> Json {
    let a = c.alpha();
    let r = c.red();
    let g = c.green();
    let b = c.blue();
    if a == 255 {
        Json::String(format!("#{r:02x}{g:02x}{b:02x}"))
    } else {
        Json::String(format!("#{r:02x}{g:02x}{b:02x}{a:02x}"))
    }
}

fn color_from_json(v: &Json) -> Result<Color, String> {
    let s = v.as_str().ok_or_else(|| format!("expected color string, got {v}"))?;
    parse_color_literal(s).ok_or_else(|| format!("Failed to parse color: {s}"))
}

fn brush_to_json(b: &Brush) -> Result<Json, String> {
    match b {
        Brush::SolidColor(c) => Ok(color_to_json(c)),
        Brush::LinearGradient(lg) => {
            let mut gradient = format!("@linear-gradient({}deg", lg.angle());
            for stop in lg.stops() {
                gradient.push_str(&format!(", {} {}%", color_to_string(&stop.color), stop.position * 100.0));
            }
            gradient.push(')');
            Ok(Json::String(gradient))
        }
        Brush::RadialGradient(rg) => {
            let mut gradient = "@radial-gradient(circle".to_string();
            for stop in rg.stops() {
                gradient.push_str(&format!(", {} {}%", color_to_string(&stop.color), stop.position * 100.0));
            }
            gradient.push(')');
            Ok(Json::String(gradient))
        }
        _ => Err("Cannot serialize an unknown brush type".into()),
    }
}

fn color_to_string(color: &Color) -> String {
    let a = color.alpha();
    let r = color.red();
    let g = color.green();
    let b = color.blue();
    if a == 255 {
        format!("#{r:02x}{g:02x}{b:02x}")
    } else {
        format!("#{r:02x}{g:02x}{b:02x}{a:02x}")
    }
}

fn brush_from_json(v: &Json) -> Result<Brush, String> {
    let s = v.as_str().ok_or_else(|| format!("expected brush string, got {v}"))?;
    if s.starts_with('#') {
        return Ok(Brush::SolidColor(color_from_json(v)?));
    }
    let Some(input) = s.strip_suffix(')') else {
        return Err(format!("No closing ')' in '{s}'"));
    };
    if let Some(linear) = input.strip_prefix("@linear-gradient(") {
        let mut split = linear.split(',').map(str::trim);
        let angle_part = split.next().ok_or_else(|| {
            "A linear gradient must start with an angle in 'deg'".to_string()
        })?;
        let angle = angle_part
            .strip_suffix("deg")
            .ok_or_else(|| "A linear brush needs to start with an angle in 'deg'".to_string())
            .and_then(|no| no.parse::<f32>().map_err(|_| "Failed to parse angle value".into()))?;
        let stops = parse_gradient_stops(split)?;
        return Ok(Brush::LinearGradient(slint::private_unstable_api::re_exports::LinearGradientBrush::new(angle, stops)));
    }
    if let Some(radial) = input.strip_prefix("@radial-gradient(circle") {
        let split = radial.split(',').map(str::trim);
        let stops = parse_gradient_stops(split)?;
        return Ok(Brush::RadialGradient(slint::private_unstable_api::re_exports::RadialGradientBrush::new_circle(stops)));
    }
    Err(format!("Could not parse gradient from '{input}'"))
}

fn parse_gradient_stops<'a>(
    it: impl Iterator<Item = &'a str>,
) -> Result<Vec<slint::private_unstable_api::re_exports::GradientStop>, String> {
    it.filter(|part| !part.is_empty())
        .map(|part| {
            let sub_parts: Vec<_> = part.split_whitespace().collect();
            if sub_parts.len() != 2 {
                return Err("A gradient stop must consist of a color and a position in '%' separated by whitespace".into());
            }
            let color = parse_color_literal(sub_parts[0])
                .ok_or_else(|| format!("'{}' is not a color", sub_parts[0]))?;
            let position = sub_parts[1]
                .strip_suffix('%')
                .ok_or_else(|| format!("The position '{}' does not end in '%'", sub_parts[1]))
                .and_then(|percent_value| {
                    percent_value
                        .parse::<f32>()
                        .map_err(|_| format!("Could not parse position '{}' as number", sub_parts[1]))
                })?;
            Ok(slint::private_unstable_api::re_exports::GradientStop {
                color,
                position: position / 100.0,
            })
        })
        .collect()
}

fn image_to_json(img: &Image) -> Result<Json, String> {
    img.path()
        .map(|p| Json::String(p.to_string_lossy().into_owned()))
        .ok_or_else(|| "Cannot serialize an image without a path".into())
}

fn image_from_json(v: &Json) -> Result<Image, String> {
    let s = v.as_str().ok_or_else(|| format!("expected image path string, got {v}"))?;
    Image::load_from_path(std::path::Path::new(s))
        .map_err(|e| format!("Failed to load image from path: {s}: {e}"))
}


fn cstr<'a>(p: *const c_char, what: &str) -> Result<&'a str, String> {
    if p.is_null() {
        return Err(format!("{what} is null"));
    }
    unsafe { CStr::from_ptr(p) }
        .to_str()
        .map_err(|_| format!("{what} is not valid UTF-8"))
}

fn json_out(v: Json) -> *mut c_char {
    match CString::new(v.to_string()) {
        Ok(c) => c.into_raw(),
        Err(_) => {
            set_error("output contains null byte".into());
            ptr::null_mut()
        }
    }
}

#[no_mangle]
pub extern "C" fn slint_aot_string_free(s: *mut c_char) {
    if !s.is_null() {
        let _ = catch_unwind(|| drop(unsafe { CString::from_raw(s) }));
    }
}

#[no_mangle]
pub extern "C" fn slint_aot_last_error() -> *mut c_char {
    match take_error() {
        Some(err) => CString::new(err).map(|c| c.into_raw()).unwrap_or(ptr::null_mut()),
        None => ptr::null_mut(),
    }
}

/// Sets the return value (JSON) of the host callback running right now.
/// The string is copied; null clears it.
#[no_mangle]
pub extern "C" fn slint_aot_callback_set_result(json: *const c_char) {
    if !on_owner_thread() {
        return;
    }
    let _ = catch_unwind(|| {
        let value = if json.is_null() {
            None
        } else {
            unsafe { CStr::from_ptr(json) }.to_str().ok().map(str::to_string)
        };
        CALLBACK_RESULT.with(|r| *r.borrow_mut() = value);
    });
}

/// Runs the host callback and takes the result it set, if any.
fn call_host(cb: SlintAotCallbackFn, ud: usize, args: Json) -> Option<Json> {
    let c = CString::new(args.to_string()).ok()?;
    CALLBACK_RESULT.with(|r| r.borrow_mut().take());
    cb(ud as *mut c_void, c.as_ptr());
    let result = CALLBACK_RESULT.with(|r| r.borrow_mut().take())?;
    serde_json::from_str(&result).ok()
}
''');

  // Struct/enum converters, deduplicated by name across all files.
  final structs = <String, TypeRef>{};
  final enums = <String, TypeRef>{};
  for (final f in files) {
    for (final c in f.schema.components) {
      for (final p in c.properties) {
        _collectSchemaTypes(p.type, structs, enums);
      }
      for (final cb in c.callbacks) {
        for (final a in cb.args) {
          _collectSchemaTypes(a.type, structs, enums);
        }
        if (cb.returnType != null) {
          _collectSchemaTypes(cb.returnType!, structs, enums);
        }
      }
    }
  }
  for (final e in enums.values) {
    b.write(_enumHelpers(e));
  }
  for (final s in structs.values) {
    b.write(_structHelpers(s));
  }

  final seenComponents = <String>{};
  for (final f in files) {
    for (final c in f.schema.components) {
      if (!seenComponents.add(c.name)) {
        throw StateError(
          'component ${c.name} is exported by more than one .slint file; '
          'component names must be unique across the package',
        );
      }
      b.write(_componentGlue(c));
    }
  }

  return b.toString();
}

void _collectSchemaTypes(
  TypeRef t,
  Map<String, TypeRef> structs,
  Map<String, TypeRef> enums,
) {
  if (t.kind == 'struct') {
    structs.putIfAbsent(t.structName!, () => t);
    for (final f in t.fields!) {
      _collectSchemaTypes(f.type, structs, enums);
    }
  } else if (t.kind == 'enum') {
    enums.putIfAbsent(t.enumName!, () => t);
  } else if (t.kind == 'array') {
    _collectSchemaTypes(t.element!, structs, enums);
  }
}

/// Rust type of a schema type, as slint's Rust generator produces it.
String _rustType(TypeRef t) => switch (t.kind) {
  'float' || 'length' || 'angle' || 'percent' => 'f32',
  'duration' => 'i64',
  'int' => 'i32',
  'string' => 'SharedString',
  'bool' => 'bool',
  'color' => 'Color',
  'brush' => 'Brush',
  'image' => 'Image',
  'enum' => rustIdent(t.enumName!),
  'struct' => rustIdent(t.structName!),
  'array' => 'ModelRc<${_rustType(t.element!)}>',
  _ => throw StateError('unsupported type kind: ${t.kind}'),
};

/// Rust expression converting owned value [expr] of type [t] to `Json`.
String _toJson(String expr, TypeRef t) => switch (t.kind) {
  'float' ||
  'length' ||
  'angle' ||
  'percent' ||
  'duration' ||
  'int' => 'num_json(($expr) as f64)',
  'string' => 'Json::String(($expr).to_string())',
  'bool' => 'Json::Bool($expr)',
  'color' => 'color_to_json(&$expr)',
  'brush' => 'brush_to_json(&$expr)?',
  'image' => 'image_to_json(&$expr)?',
  'enum' => '${snakeFromPascal(t.enumName!)}_to_json(&$expr)',
  'struct' => '${snakeFromPascal(t.structName!)}_to_json(&($expr))',
  'array' =>
    'Json::Array(($expr).iter().map(|x| ${_toJson('x', t.element!)}).collect::<Vec<_>>())',
  _ => throw StateError('unsupported type kind: ${t.kind}'),
};

/// Rust expression (containing `?`) converting `&Json` [expr] to type [t].
String _fromJson(String expr, TypeRef t) => switch (t.kind) {
  'float' || 'length' || 'angle' || 'percent' => '(json_number($expr)? as f32)',
  'duration' => '(json_number($expr)? as i64)',
  'int' => '(json_number($expr)? as i32)',
  'string' =>
    'SharedString::from(($expr).as_str().ok_or_else(|| format!("expected string, got {}", $expr))?)',
  'bool' =>
    '($expr).as_bool().ok_or_else(|| format!("expected bool, got {}", $expr))?',
  'color' => 'color_from_json($expr)?',
  'brush' => 'brush_from_json($expr)?',
  'image' => 'image_from_json($expr)?',
  'enum' => '${snakeFromPascal(t.enumName!)}_from_json($expr)?',
  'struct' => '${snakeFromPascal(t.structName!)}_from_json($expr)?',
  'array' =>
    '''
{
        let arr = ($expr).as_array().ok_or_else(|| format!("expected array, got {}", $expr))?;
        let mut v: Vec<${_rustType(t.element!)}> = Vec::with_capacity(arr.len());
        for item in arr {
            v.push(${_fromJson('item', t.element!)});
        }
        ModelRc::new(VecModel::from(v))
    }''',
  _ => throw StateError('unsupported type kind: ${t.kind}'),
};

String _enumHelpers(TypeRef e) {
  final pascal = rustIdent(e.enumName!);
  final snake = snakeFromPascal(e.enumName!);
  final variants = e.variants!;
  final fromArms = variants
      .map((v) => '        "$v" => Ok($pascal::${enumVariantRustIdent(v)}),')
      .join('\n');
  final toArms = variants
      .map(
        (v) =>
            '        $pascal::${enumVariantRustIdent(v)} => Json::String("${e.enumName}.$v".into()),',
      )
      .join('\n');
  return '''

fn ${snake}_from_json(v: &Json) -> Result<$pascal, String> {
    let s = v.as_str().ok_or_else(|| format!("expected enum string, got {v}"))?;
    let suffix = s.strip_prefix("${e.enumName}.").unwrap_or(s);
    match suffix {
$fromArms
        _ => Err(format!("Unexpected value for enum '${e.enumName}': {s}")),
    }
}

fn ${snake}_to_json(v: &$pascal) -> Json {
    match v {
$toArms
    }
}
''';
}

String _structHelpers(TypeRef s) {
  final pascal = rustIdent(s.structName!);
  final snake = snakeFromPascal(s.structName!);
  final fromFields = s.fields!
      .map(
        (f) =>
            '''
    if let Some(f) = obj.get("${f.name}") {
        out.${rustIdent(f.name)} = ${_fromJson('f', f.type)};
    }''',
      )
      .join('\n');
  final toFields = s.fields!
      .map(
        (f) =>
            '    obj.insert("${f.name}".into(), ${_toJson('v.${rustIdent(f.name)}.clone()', f.type)});',
      )
      .join('\n');
  return '''

fn ${snake}_from_json(v: &Json) -> Result<$pascal, String> {
    let obj = v.as_object().ok_or_else(|| format!("expected object for $pascal, got {v}"))?;
    let mut out = $pascal::default();
$fromFields
    Ok(out)
}

fn ${snake}_to_json(v: &$pascal) -> Json {
    let mut obj = serde_json::Map::new();
$toFields
    Json::Object(obj)
}
''';
}

String _componentGlue(ComponentSchema c) {
  final ty = rustIdent(c.name);
  final handle = '${ty}AotHandle';
  final p = 'slint_aot_${snakeFromPascal(c.name)}';

  final getArms = c.properties
      .map(
        (prop) =>
            '            "${prop.name}" => Ok(${_toJson('handle.inst.get_${rustIdent(prop.name)}()', prop.type)}),',
      )
      .join('\n');
  final setArms = c.properties
      .map(
        (prop) =>
            '''
            "${prop.name}" => {
                handle.inst.set_${rustIdent(prop.name)}(${_fromJson('&val', prop.type)});
                Ok(true)
            }''',
      )
      .join('\n');

  final invokeArms = c.callbacks
      .map((cb) {
        final argLets = [
          for (var i = 0; i < cb.args.length; i++)
            '                let a$i = ${_fromJson('args.get($i).unwrap_or(&Json::Null)', cb.args[i].type)};',
        ].join('\n');
        final call =
            'handle.inst.invoke_${rustIdent(cb.name)}(${[for (var i = 0; i < cb.args.length; i++) 'a$i'].join(', ')})';
        final body = cb.returnType == null
            ? '                $call;\n                Ok(Json::Null)'
            : '                let r = $call;\n                Ok(${_toJson('r', cb.returnType!)})';
        return '''
            "${cb.name}" => {
$argLets
$body
            }''';
      })
      .join('\n');

  final callbackArms = c.callbacks
      .map((cb) {
        final params = [for (var i = 0; i < cb.args.length; i++) 'arg$i']
            .join(', ');
        final argsJson = [
          for (var i = 0; i < cb.args.length; i++)
            _toJson('arg$i', cb.args[i].type),
        ].join(', ');
        final call = 'call_host(cb, ud, Json::Array(vec![$argsJson]))';
        // A result the handler did not set, or one of the wrong shape, reads
        // as the declared type's default — what Slint uses for "no value".
        final body = cb.returnType == null
            ? '$call;'
            : '''
$call
                        .and_then(|ret_json| {
                            (|| -> Result<${_rustType(cb.returnType!)}, String> {
                                Ok(${_fromJson('&ret_json', cb.returnType!)})
                            })()
                            .ok()
                        })
                        .unwrap_or_default()''';
        return '''
            "${cb.name}" => {
                let ud = user_data as usize;
                handle.inst.on_${rustIdent(cb.name)}(move |$params| {
                    $body
                });
                Ok(true)
            }''';
      })
      .join('\n');

  return '''

// === ${c.name} ===

struct $handle {
    inst: $ty,
    window: Rc<MinimalSoftwareWindow>,
}

#[no_mangle]
pub extern "C" fn ${p}_new() -> *mut c_void {
    clear_error();
    if !on_owner_thread() {
        return ptr::null_mut();
    }
    ensure_platform_initialized();
    match catch_unwind(|| -> Result<*mut c_void, String> {
        let inst = $ty::new().map_err(|e| format!("{e:?}"))?;
        inst.show().map_err(|e| format!("{e:?}"))?;
        let window = NEXT_WINDOW
            .with(|s| s.borrow_mut().take())
            .ok_or_else(|| "platform did not create a window".to_string())?;
        Ok(Box::into_raw(Box::new($handle { inst, window })) as *mut c_void)
    }) {
        Ok(Ok(ptr)) => ptr,
        Ok(Err(e)) => {
            set_error(e);
            ptr::null_mut()
        }
        Err(_) => {
            set_error("panicked in ${p}_new".into());
            ptr::null_mut()
        }
    }
}

#[no_mangle]
pub extern "C" fn ${p}_free(h: *mut c_void) {
    if !on_owner_thread() {
        return;
    }
    if !h.is_null() {
        let _ = catch_unwind(|| {
            let handle = unsafe { Box::from_raw(h as *mut $handle) };
            // show() parked a strong reference in the window; without hide()
            // the component, its timers and its callbacks outlive the free.
            let _ = handle.inst.hide();
            drop(handle);
        });
    }
}

#[no_mangle]
pub extern "C" fn ${p}_set_size(h: *mut c_void, width: u32, height: u32) {
    if !on_owner_thread() {
        return;
    }
    if h.is_null() {
        return;
    }
    let _ = catch_unwind(|| {
        let handle = unsafe { &*(h as *const $handle) };
        handle.window.set_size(PhysicalSize::new(width, height));
    });
}

#[no_mangle]
pub extern "C" fn ${p}_render(h: *mut c_void, buffer: *mut u8, len: usize) -> bool {
    clear_error();
    if !on_owner_thread() {
        return false;
    }
    if h.is_null() || buffer.is_null() {
        return false;
    }
    match catch_unwind(|| {
        let handle = unsafe { &*(h as *const $handle) };
        let size = handle.window.size();
        let expected_len = (size.width as usize) * (size.height as usize) * 4;
        if len != expected_len {
            set_error(format!("buffer size mismatch: expected {expected_len}, got {len}"));
            return false;
        }
        let pixels = unsafe {
            std::slice::from_raw_parts_mut(buffer as *mut PremultipliedRgbaColor, len / 4)
        };
        slint::platform::update_timers_and_animations();
        let mut drawn = false;
        handle.window.draw_if_needed(|renderer| {
            renderer.render(pixels, size.width as usize);
            drawn = true;
        });
        drawn
    }) {
        Ok(result) => result,
        Err(_) => {
            set_error("panicked in ${p}_render".into());
            false
        }
    }
}

#[no_mangle]
pub extern "C" fn ${p}_pointer_event(
    h: *mut c_void,
    kind: u8,
    x: f32,
    y: f32,
    button: u8,
    dx: f32,
    dy: f32,
) {
    if !on_owner_thread() {
        return;
    }
    if h.is_null() {
        return;
    }
    let _ = catch_unwind(|| {
        if let Some(event) = slint_dart_core::events::pointer_event(kind, x, y, button, dx, dy) {
            let handle = unsafe { &*(h as *const $handle) };
            let _ = handle.window.dispatch_event(event);
        }
    });
}

#[no_mangle]
pub extern "C" fn ${p}_key_event(h: *mut c_void, text: *const c_char, pressed: bool) {
    if !on_owner_thread() {
        return;
    }
    if h.is_null() || text.is_null() {
        return;
    }
    let _ = catch_unwind(|| {
        if let Ok(text_str) = unsafe { CStr::from_ptr(text) }.to_str() {
            let event = slint_dart_core::events::key_event(text_str, pressed);
            let handle = unsafe { &*(h as *const $handle) };
            let _ = handle.window.dispatch_event(event);
        }
    });
}

#[no_mangle]
pub extern "C" fn ${p}_get_property(h: *mut c_void, name: *const c_char) -> *mut c_char {
    clear_error();
    if !on_owner_thread() {
        return ptr::null_mut();
    }
    if h.is_null() {
        return ptr::null_mut();
    }
    match catch_unwind(|| -> Result<Json, String> {
        let name = cstr(name, "property name")?;
        let handle = unsafe { &*(h as *const $handle) };
        match name {
$getArms
            _ => Err(format!("unknown property '{name}'")),
        }
    }) {
        Ok(Ok(v)) => json_out(v),
        Ok(Err(e)) => {
            set_error(e);
            ptr::null_mut()
        }
        Err(_) => {
            set_error("panicked in ${p}_get_property".into());
            ptr::null_mut()
        }
    }
}

#[no_mangle]
pub extern "C" fn ${p}_set_property(h: *mut c_void, name: *const c_char, json: *const c_char) -> bool {
    clear_error();
    if !on_owner_thread() {
        return false;
    }
    if h.is_null() {
        return false;
    }
    match catch_unwind(|| -> Result<bool, String> {
        let name = cstr(name, "property name")?;
        let val: Json = serde_json::from_str(cstr(json, "property json")?)
            .map_err(|e| format!("invalid JSON for property '{name}': {e}"))?;
        let handle = unsafe { &*(h as *const $handle) };
        match name {
$setArms
            _ => Err(format!("unknown property '{name}'")),
        }
    }) {
        Ok(Ok(ok)) => ok,
        Ok(Err(e)) => {
            set_error(e);
            false
        }
        Err(_) => {
            set_error("panicked in ${p}_set_property".into());
            false
        }
    }
}

#[no_mangle]
pub extern "C" fn ${p}_invoke(h: *mut c_void, name: *const c_char, args_json: *const c_char) -> *mut c_char {
    clear_error();
    if !on_owner_thread() {
        return ptr::null_mut();
    }
    if h.is_null() {
        return ptr::null_mut();
    }
    match catch_unwind(|| -> Result<Json, String> {
        let name = cstr(name, "callback name")?;
        let args: Json = serde_json::from_str(cstr(args_json, "args json")?)
            .map_err(|e| format!("invalid args JSON for '{name}': {e}"))?;
        let args = args
            .as_array()
            .ok_or_else(|| "args_json must be a JSON array".to_string())?;
        let handle = unsafe { &*(h as *const $handle) };
        match name {
$invokeArms
            _ => Err(format!("unknown callback '{name}'")),
        }
    }) {
        Ok(Ok(v)) => json_out(v),
        Ok(Err(e)) => {
            set_error(e);
            ptr::null_mut()
        }
        Err(_) => {
            set_error("panicked in ${p}_invoke".into());
            ptr::null_mut()
        }
    }
}

#[no_mangle]
pub extern "C" fn ${p}_set_callback(
    h: *mut c_void,
    name: *const c_char,
    cb: SlintAotCallbackFn,
    user_data: *mut c_void,
) -> bool {
    clear_error();
    if !on_owner_thread() {
        return false;
    }
    if h.is_null() {
        return false;
    }
    match catch_unwind(|| -> Result<bool, String> {
        let name = cstr(name, "callback name")?;
        let handle = unsafe { &*(h as *const $handle) };
        match name {
$callbackArms
            _ => Err(format!("unknown callback '{name}'")),
        }
    }) {
        Ok(Ok(ok)) => ok,
        Ok(Err(e)) => {
            set_error(e);
            false
        }
        Err(_) => {
            set_error("panicked in ${p}_set_callback".into());
            false
        }
    }
}
''';
}
