import 'dart:convert';

import 'names.dart';
import 'schema.dart';

/// Generates the typed wrapper library for one `.slint` file.
///
/// One class per exported component, with typed property accessors and
/// callback helpers over the `SlintComponent` interface — backend-agnostic:
/// instances come from a `SlintComponentFactory`, so the same wrapper runs on
/// the interpreter (`slint_interpreter`) or on AOT-compiled code
/// (`slint_compiler`). [slintSource] is embedded for the backends that
/// compile at runtime; [sourceName] only labels the generated header.
///
/// [aotLibrary] names the sibling `*.aot.g.dart` when the package depends on
/// `slint_compiler`, and [interpreter] says whether it depends on
/// `slint_interpreter`. Whichever backends are available become the default of
/// `create()`, so callers need no wiring; with both, the default follows the
/// build mode, exactly like the hooks deciding which dylib to bundle.
String generateWrapperLibrary(
  SlintSchema schema, {
  required String sourceName,
  required String slintSource,
  String? aotLibrary,
  bool interpreter = false,
}) {
  final imports = StringBuffer("import 'package:slint/slint_core.dart';\n"
      "import 'package:slint_generator/runtime.dart';\n");
  if (interpreter) {
    imports
        .write("import 'package:slint_interpreter/slint_interpreter.dart';\n");
  }
  if (aotLibrary != null) {
    imports.write("\nimport '$aotLibrary' as aot;\n");
  }

  final b = StringBuffer('''
// GENERATED by slint_generator from $sourceName — do not edit.
// ignore_for_file: type=lint
library;

$imports
/// `$sourceName`, embedded so interpreter backends can compile it at runtime.
const _source = ${dartStringLiteral(slintSource)};
''');

  if (interpreter && aotLibrary != null) {
    b.write('''

/// True in release and profile builds — the same condition the build hooks
/// use (`linkingEnabled`) to bundle the AOT dylib instead of the interpreter,
/// spelled without a Flutter import.
const _useCompiled = bool.fromEnvironment('dart.vm.product') ||
    bool.fromEnvironment('dart.vm.profile');
''');
  }

  for (final component in schema.components) {
    b.write(_componentDart(
      component,
      sourceName,
      aotLibrary: aotLibrary,
      interpreter: interpreter,
    ));
  }
  return b.toString();
}

/// Encodes [value] as a Dart string literal (JSON escaping plus `$`, which
/// Dart would otherwise read as interpolation).
String dartStringLiteral(String value) =>
    jsonEncode(value).replaceAll(r'$', r'\$');

String _componentDart(
  ComponentSchema component,
  String sourceName, {
  required String? aotLibrary,
  required bool interpreter,
}) {
  final pascal = component.name;
  final members = StringBuffer();

  for (final prop in component.properties) {
    final name = camelCase(prop.name);
    final (dartType, read) = switch (prop.type.kind) {
      'float' || 'length' || 'angle' || 'percent' || 'duration' => (
          'double',
          "(component.getProperty('${prop.name}') as num).toDouble()"
        ),
      'int' => ('int', "(component.getProperty('${prop.name}') as num).toInt()"),
      'string' => ('String', "component.getProperty('${prop.name}') as String"),
      'bool' => ('bool', "component.getProperty('${prop.name}') as bool"),
      'array' => (
          'List<Object?>',
          "component.getProperty('${prop.name}') as List<Object?>"
        ),
      'struct' => (
          'Map<Object?, Object?>',
          "component.getProperty('${prop.name}') as Map<Object?, Object?>"
        ),
      _ => throw StateError('unsupported property type: ${prop.type.kind}'),
    };
    members.write('''

  $dartType get $name => $read;
  set $name($dartType value) => component.setProperty('${prop.name}', value);
''');
  }

  for (final cb in component.callbacks) {
    final p = pascalCase(cb.name);
    members.write('''

  void on$p(SlintCallbackHandler handler) =>
      component.setCallbackHandler('${cb.name}', handler);
  Object? invoke$p([List<Object?> arguments = const []]) =>
      component.invokeCallback('${cb.name}', arguments);
''');
  }

  final aotFactory = aotLibrary == null ? null : 'aot.${aotFactoryName(pascal)}';
  final (defaultFactory, defaultDoc) = switch ((aotFactory, interpreter)) {
    (final String f, true) => (
        '_useCompiled ? $f : SlintInterpreterFactory()',
        'the AOT-compiled component in release and profile builds, the\n'
            '  /// interpreter in debug — matching the dylib the build actually bundles',
      ),
    (final String f, false) => (f, 'the AOT-compiled component'),
    (null, true) => ('SlintInterpreterFactory()', 'the interpreter'),
    (null, false) => (null, ''),
  };

  final create = defaultFactory == null
      ? '''
  /// Instantiates `$pascal` through [factory].
  static Future<$pascal> create(SlintComponentFactory factory) async =>
      $pascal(await factory.instantiate(_source, componentName));
'''
      : '''
  /// Backend [create] uses when given none: $defaultDoc.
  ///
  /// Created once, on first use, and shared by every instance.
  static final SlintComponentFactory defaultFactory = $defaultFactory;

  /// Instantiates `$pascal` through [factory], or [defaultFactory].
  static Future<$pascal> create([SlintComponentFactory? factory]) async =>
      $pascal(await (factory ?? defaultFactory)
          .instantiate(_source, componentName));
''';

  final example = defaultFactory == null
      ? 'final app = await $pascal.create(SlintInterpreterFactory());'
      : 'final app = await $pascal.create();';

  return '''

/// Typed wrapper for the `$pascal` component of `$sourceName`.
///
/// ```dart
/// $example
/// ```
class $pascal {
  $pascal(this.component);

  /// Name of the exported component this wrapper drives.
  static const componentName = '$pascal';

  /// The `.slint` source this wrapper was generated from.
  static const slintSource = _source;

$create
  /// The backing instance — use it for untyped property/callback access.
  final SlintSoftwareComponent component;

  SlintSoftwareRenderTarget get renderTarget => component.renderTarget;

  void dispose() => component.dispose();
$members}
''';
}
