import 'dart:convert';

import 'names.dart';
import 'schema.dart';

/// Generates the typed wrapper library for one `.slint` file.
///
/// One class per exported component, with typed property accessors and
/// callback helpers over the `SlintComponent` interface — backend-agnostic:
/// instances come from a `SlintComponentFactory`, so the same wrapper runs on
/// the interpreter (`slint_interpreter`) or on AOT-compiled code
/// (`slint_compiler`). [slintSource] is embedded for the backends that
/// compile at runtime; [sourceName] only labels the generated header.
String generateWrapperLibrary(
  SlintSchema schema, {
  required String sourceName,
  required String slintSource,
}) {
  final b = StringBuffer('''
// GENERATED by slint_generator from $sourceName — do not edit.
// ignore_for_file: type=lint
library;

import 'package:slint/slint_core.dart';

/// `$sourceName`, embedded so interpreter backends can compile it at runtime.
const _source = ${dartStringLiteral(slintSource)};
''');

  for (final component in schema.components) {
    b.write(_componentDart(component, sourceName));
  }
  return b.toString();
}

/// Encodes [value] as a Dart string literal (JSON escaping plus `$`, which
/// Dart would otherwise read as interpolation).
String dartStringLiteral(String value) =>
    jsonEncode(value).replaceAll(r'$', r'\$');

String _componentDart(ComponentSchema component, String sourceName) {
  final pascal = component.name;
  final members = StringBuffer();

  for (final prop in component.properties) {
    final name = camelCase(prop.name);
    final (dartType, read) = switch (prop.type.kind) {
      'float' || 'length' || 'angle' || 'percent' || 'duration' => (
          'double',
          "(component.getProperty('${prop.name}') as num).toDouble()"
        ),
      'int' => ('int', "(component.getProperty('${prop.name}') as num).toInt()"),
      'string' => ('String', "component.getProperty('${prop.name}') as String"),
      'bool' => ('bool', "component.getProperty('${prop.name}') as bool"),
      'array' => (
          'List<Object?>',
          "component.getProperty('${prop.name}') as List<Object?>"
        ),
      'struct' => (
          'Map<Object?, Object?>',
          "component.getProperty('${prop.name}') as Map<Object?, Object?>"
        ),
      _ => throw StateError('unsupported property type: ${prop.type.kind}'),
    };
    members.write('''

  $dartType get $name => $read;
  set $name($dartType value) => component.setProperty('${prop.name}', value);
''');
  }

  for (final cb in component.callbacks) {
    final p = pascalCase(cb.name);
    members.write('''

  void on$p(SlintCallbackHandler handler) =>
      component.setCallbackHandler('${cb.name}', handler);
  Object? invoke$p([List<Object?> arguments = const []]) =>
      component.invokeCallback('${cb.name}', arguments);
''');
  }

  return '''

/// Typed wrapper for the `$pascal` component of `$sourceName`.
///
/// Create it through the factory of the backend you want:
///
/// ```dart
/// final app = await $pascal.create(SlintInterpreterFactory());
/// ```
class $pascal {
  $pascal(this.component);

  /// Name of the exported component this wrapper drives.
  static const componentName = '$pascal';

  /// The `.slint` source this wrapper was generated from.
  static const slintSource = _source;

  /// Instantiates `$pascal` through [factory].
  static Future<$pascal> create(SlintComponentFactory factory) async =>
      $pascal(await factory.instantiate(_source, componentName));

  /// The backing instance — use it for untyped property/callback access.
  final SlintSoftwareComponent component;

  SlintSoftwareRenderTarget get renderTarget => component.renderTarget;

  void dispose() => component.dispose();
$members}
''';
}
