import 'package:slint/slint_core.dart';

/// Creates instances of a component for one backend.
///
/// The typed wrappers generated by this package take a factory, so the same
/// generated API runs on either backend — `SlintInterpreterFactory`
/// (`slint_interpreter`) compiles the embedded source at runtime,
/// `SlintCompilerFactory` (`slint_compiler`) binds AOT-compiled code:
///
/// ```dart
/// final app = await TodoApp.create(SlintInterpreterFactory());
/// ```
///
/// `base` on purpose: a backend must `extend` this, so every factory is a real
/// subtype rather than a structural look-alike.
abstract base class SlintComponentFactory {
  const SlintComponentFactory();

  /// Instantiates the component named [componentName]. [source] is the
  /// `.slint` source embedded in the generated wrapper: interpreter backends
  /// compile it at runtime, AOT backends already contain the component and
  /// ignore it.
  Future<SlintSoftwareComponent> instantiate(
    String source,
    String componentName,
  );
}
