// GENERATED by slint_compiler from todo.slint — do not edit.
// ignore_for_file: type=lint
@ffi.DefaultAsset('package:todo_example/todo.aot.g.dart')
library;

import 'dart:ffi' as ffi;

import 'package:meta/meta.dart' show RecordUse;
import 'package:slint_compiler/runtime.dart';

@ffi.Native<ffi.Pointer<ffi.Char> Function()>(symbol: 'slint_aot_last_error')
external ffi.Pointer<ffi.Char> _lastError();

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>(symbol: 'slint_aot_string_free')
external void _stringFree(ffi.Pointer<ffi.Char> s);

// === TodoApp ===

// Liveness anchor: the factory below tears this off, so the AOT link hook
// sees a recorded use exactly when this component is reachable — and drops
// its native code from the dylib when it is not.
@RecordUse()
@ffi.Native<ffi.Pointer<ffi.Void> Function()>(symbol: 'slint_aot_todo_app_new')
external ffi.Pointer<ffi.Void> _todoAppNew();

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(symbol: 'slint_aot_todo_app_free')
external void _todoAppFree(ffi.Pointer<ffi.Void> handle);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Uint32, ffi.Uint32)>(symbol: 'slint_aot_todo_app_set_size')
external void _todoAppSetSize(ffi.Pointer<ffi.Void> handle, int width, int height);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Uint8>, ffi.Size)>(symbol: 'slint_aot_todo_app_render')
external bool _todoAppRender(ffi.Pointer<ffi.Void> handle, ffi.Pointer<ffi.Uint8> buffer, int len);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Uint8, ffi.Float, ffi.Float, ffi.Uint8, ffi.Float, ffi.Float)>(symbol: 'slint_aot_todo_app_pointer_event')
external void _todoAppPointerEvent(ffi.Pointer<ffi.Void> handle, int kind, double x, double y, int button, double dx, double dy);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Bool)>(symbol: 'slint_aot_todo_app_key_event')
external void _todoAppKeyEvent(ffi.Pointer<ffi.Void> handle, ffi.Pointer<ffi.Char> text, bool pressed);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>)>(symbol: 'slint_aot_todo_app_get_property')
external ffi.Pointer<ffi.Char> _todoAppGetProperty(ffi.Pointer<ffi.Void> handle, ffi.Pointer<ffi.Char> name);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>(symbol: 'slint_aot_todo_app_set_property')
external bool _todoAppSetProperty(ffi.Pointer<ffi.Void> handle, ffi.Pointer<ffi.Char> name, ffi.Pointer<ffi.Char> json);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>(symbol: 'slint_aot_todo_app_invoke')
external ffi.Pointer<ffi.Char> _todoAppInvoke(ffi.Pointer<ffi.Void> handle, ffi.Pointer<ffi.Char> name, ffi.Pointer<ffi.Char> argsJson);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.NativeFunction<SlintAotCallbackNative>>, ffi.Pointer<ffi.Void>)>(symbol: 'slint_aot_todo_app_set_callback')
external bool _todoAppSetCallback(ffi.Pointer<ffi.Void> handle, ffi.Pointer<ffi.Char> name, ffi.Pointer<ffi.NativeFunction<SlintAotCallbackNative>> cb, ffi.Pointer<ffi.Void> userData);

/// AOT backend for `TodoApp`: instantiates the slint-build compiled component
/// from the app's `slint-dart-aot` code asset, no interpreter involved.
///
/// Pass it to the generated wrapper: `await TodoApp.create(todoAppFactory)`
/// — or just `await TodoApp.create()`, which defaults to it in release builds.
final todoAppFactory = SlintCompilerFactory(
  componentName: 'TodoApp',
  ops: SlintComponentOps(
    lastError: _lastError,
    stringFree: _stringFree,
    create: _todoAppNew,
    free: _todoAppFree,
    setSize: _todoAppSetSize,
    render: _todoAppRender,
    pointerEvent: _todoAppPointerEvent,
    keyEvent: _todoAppKeyEvent,
    getProperty: _todoAppGetProperty,
    setProperty: _todoAppSetProperty,
    invoke: _todoAppInvoke,
    setCallback: _todoAppSetCallback,
  ),
);
