// GENERATED by slint_compiler from todo.slint — do not edit.
//
// Regenerate with: dart run slint_compiler todo.slint
// ignore_for_file: type=lint

import 'package:slint/slint_core.dart';
import 'package:slint_native/slint_native.dart';

const String _slintSource = "import { Button, CheckBox, LineEdit, ListView, VerticalBox, HorizontalBox } from \"std-widgets.slint\";\n\nexport struct TodoItem {\n    title: string,\n    checked: bool,\n}\n\nexport component TodoApp inherits Window {\n    preferred-width: 400px;\n    preferred-height: 600px;\n    title: \"Slint ♥ Flutter — Todo\";\n\n    // Host (Dart) owns the list; this default renders before the host syncs.\n    in property <[TodoItem]> todo-model: [\n        { title: \"Wire Slint into Flutter\", checked: true },\n        { title: \"Render this list\", checked: false },\n    ];\n\n    callback add-todo(string);\n    callback toggle-todo(int, bool);\n    callback remove-done();\n\n    VerticalBox {\n        HorizontalBox {\n            padding: 0;\n            edit := LineEdit {\n                placeholder-text: \"What needs to be done?\";\n                accepted(text) => { root.add-todo(text); self.text = \"\"; }\n            }\n            Button {\n                text: \"Add\";\n                primary: true;\n                clicked => { root.add-todo(edit.text); edit.text = \"\"; }\n            }\n        }\n        ListView {\n            for item[index] in root.todo-model: HorizontalBox {\n                padding: 0;\n                CheckBox {\n                    text: item.title;\n                    checked: item.checked;\n                    toggled => { root.toggle-todo(index, self.checked); }\n                }\n            }\n        }\n        Button {\n            text: \"Remove done items\";\n            clicked => { root.remove-done(); }\n        }\n    }\n}\n";

/// Typed wrapper for the `TodoApp` component of `todo.slint`.
class TodoApp implements SlintComponent {
  TodoApp._(this._engine, this._component);

  final NativeSlintEngine _engine;
  final NativeSlintComponent _component;

  /// Compiles the embedded `.slint` source and instantiates `TodoApp`.
  static Future<TodoApp> create() async {
    final engine = NativeSlintEngine();
    try {
      final defs = await engine.compile(_slintSource, path: 'todo.slint');
      final def = defs.firstWhere(
        (d) => d.name == 'TodoApp',
        orElse: () => throw StateError('component TodoApp not found'),
      );
      final component = def.instantiate() as NativeSlintComponent;
      for (final d in defs) {
        d.dispose();
      }
      return TodoApp._(engine, component);
    } catch (_) {
      engine.dispose();
      rethrow;
    }
  }

  /// The render target to plug into `SlintView`.
  NativeSoftwareRenderTarget get renderTarget => _component.renderTarget;

  /// `todo-model` (Slint type: Model).
  List<Object?> get todoModel => _component.getProperty('todo-model') as List<Object?>;
  set todoModel(List<Object?> value) => _component.setProperty('todo-model', value);

  /// Handles the `add-todo` callback.
  void onAddTodo(SlintCallbackHandler handler) =>
      _component.setCallbackHandler('add-todo', handler);

  /// Invokes the `add-todo` callback.
  Object? invokeAddTodo([List<Object?> arguments = const []]) =>
      _component.invokeCallback('add-todo', arguments);

  /// Handles the `remove-done` callback.
  void onRemoveDone(SlintCallbackHandler handler) =>
      _component.setCallbackHandler('remove-done', handler);

  /// Invokes the `remove-done` callback.
  Object? invokeRemoveDone([List<Object?> arguments = const []]) =>
      _component.invokeCallback('remove-done', arguments);

  /// Handles the `toggle-todo` callback.
  void onToggleTodo(SlintCallbackHandler handler) =>
      _component.setCallbackHandler('toggle-todo', handler);

  /// Invokes the `toggle-todo` callback.
  Object? invokeToggleTodo([List<Object?> arguments = const []]) =>
      _component.invokeCallback('toggle-todo', arguments);

  @override
  Object? getProperty(String name) => _component.getProperty(name);

  @override
  void setProperty(String name, Object? value) =>
      _component.setProperty(name, value);

  @override
  void setCallbackHandler(String name, SlintCallbackHandler handler) =>
      _component.setCallbackHandler(name, handler);

  @override
  Object? invokeCallback(String name, List<Object?> arguments) =>
      _component.invokeCallback(name, arguments);

  @override
  void dispose() {
    _component.dispose();
    _engine.dispose();
  }
}
