import 'package:slint/slint_core.dart';
import 'package:slint_generator/runtime.dart';

import 'interpreter_engine.dart';
import 'loader.dart';

/// Interpreter backend for the wrappers generated by `slint_generator`:
/// compiles [source] — the `.slint` the wrapper embeds — at runtime.
///
/// ```dart
/// final app = TodoApp.create(SlintInterpreterFactory(TodoApp.slintSource));
/// ```
final class SlintInterpreterFactory extends SlintComponentFactory {
  /// Uses [engine] when given — otherwise creates (and owns) one.
  SlintInterpreterFactory(this.source, [InterpreterSlintEngine? engine])
      : _engine = engine ?? InterpreterSlintEngine(),
        _ownsEngine = engine == null {
    // Touching any interpreter API is enough to make SlintComponent.load work.
    useSlintInterpreter();
  }

  /// The `.slint` source every [instantiate] compiles.
  final String source;

  final InterpreterSlintEngine _engine;
  final bool _ownsEngine;

  @override
  SlintSoftwareComponent instantiate(String componentName) {
    final defs = _engine.compile(source, path: '$componentName.slint');
    try {
      for (final def in defs) {
        if (def.name == componentName) {
          return def.instantiate();
        }
      }
      throw StateError(
        "no component named '$componentName' in the compiled source "
        '(found: ${defs.map((d) => d.name).join(', ')})',
      );
    } finally {
      for (final def in defs) {
        def.dispose();
      }
    }
  }

  /// Frees the engine, if this factory created it. Components already
  /// instantiated keep working; dispose them separately.
  void dispose() {
    if (_ownsEngine) {
      _engine.dispose();
    }
  }
}
