import 'dart:convert';
import 'dart:io';

import 'package:slint_build/slint_build.dart';
import 'package:test/test.dart';

final _repo = Directory.current.uri.resolve('../../');

void main() {
  test('the staged workspace carries the repo workspace pins and lints', () {
    final root = File.fromUri(_repo.resolve('Cargo.toml')).readAsStringSync();
    expect(
      // The table header at the start of a line, not the comment naming it.
      root.substring(root.indexOf('\n[workspace.dependencies]\n') + 1),
      cargoWorkspaceShared,
      reason: 'bump the Slint pin in both places',
    );
  });

  test(
    'crates resolve from a pub cache, with no Cargo workspace around them',
    () async {
      // What pub.dev hands an app: versioned directory names, no Cargo
      // workspace above them, and slint_testing without slint_interpreter,
      // which it does not depend on.
      final tmp = Directory.systemTemp.createTempSync('slint_pub_cache_');
      addTearDown(() => tmp.deleteSync(recursive: true));
      final cache = Directory('${tmp.path}/cache');
      final packages = <Map<String, String>>[];
      for (final name in ['slint', 'slint_build', 'slint_testing']) {
        final dir = Directory('${cache.path}/$name-0.0.1')
          ..createSync(recursive: true);
        for (final crate in cargoCrates[name]!) {
          final from = _repo.resolve('packages/$name/$crate').toFilePath();
          final cp = Process.runSync('cp', ['-R', from, '${dir.path}/$crate']);
          expect(cp.exitCode, 0, reason: '${cp.stderr}');
        }
        packages.add({'name': name, 'rootUri': '${dir.uri}'});
      }
      final config = File('${tmp.path}/app/.dart_tool/package_config.json')
        ..createSync(recursive: true)
        ..writeAsStringSync(
          jsonEncode({'configVersion': 2, 'packages': packages}),
        );

      final manifest = stagedCargoManifest(config.uri, 'slint_testing');
      final staged = File.fromUri(manifest.resolve('../../../Cargo.toml'))
          .readAsStringSync();
      expect(staged, startsWith('# GENERATED by slint_build'));
      expect(staged, isNot(contains('packages/slint_interpreter')));

      final metadata = await Process.run(
        Platform.environment['CARGO'] ?? 'cargo',
        [
          'metadata',
          '--no-deps',
          '--format-version=1',
          '--manifest-path',
          manifest.toFilePath(),
        ],
      );
      expect(metadata.exitCode, 0, reason: '${metadata.stderr}');
      final names = [
        for (final p
            in (jsonDecode(metadata.stdout as String)
                    as Map<String, Object?>)['packages']
                as List)
          (p as Map<String, Object?>)['name'],
      ];
      expect(
        names,
        containsAll(['slint-testing-ffi', 'slint-dart-interpreter']),
      );

      // Staged again (the next build): nothing changes, nothing breaks.
      expect(stagedCargoManifest(config.uri, 'slint_testing'), manifest);

      expect(
        cache
            .listSync(recursive: true)
            .map((e) => e.path)
            .where(
              (path) => path.endsWith('Cargo.lock') || path.endsWith('/target'),
            ),
        isEmpty,
        reason: 'the pub cache is not ours to write',
      );
    },
  );
}
